Description of addrelpath
Home > ReBEL-0.2.7 > core > addrelpath.m
addrelpath
PURPOSE
ADDRELPATH Add a relative path which gets expanded into a absolute path
SYNOPSIS
function addrelpath(path_string)
DESCRIPTION
 ADDRELPATH  Add a relative path which gets expanded into a absolute path
             to the front of MATLABPATH.
     addrelpath(path_string)
     INPUT
            path_string        : string containing relative path
     Example : addrelpath('../foo');
     This will first expand '../foo' to an absolute path and then add it to the
     front of MATLABPATH
   See also
   REMRELPATH
   Copyright (c) Oregon Health & Science University (2006)
   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
   academic use only (see included license file) and can be obtained from
   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
   software should contact rebel@csee.ogi.edu for commercial licensing information.
   See LICENSE (which should be part of the main toolkit distribution) for more
   detail.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demspeech_dual DEMSPEECH_DUAL Sigma-Point Kalman Filter based Speech Enhancement Demonstration.
demje1 DEMJE1 Demonstrate joint estimation on a 2nd order LTI system.
demje2 DEMJE2 Demonstrate nonlinear time series joint estimation for Mackey-Glass chaotic time series
dempe1 DEMPE1 Demonstrate parameter estimation on a simple 2nd order LTI system.
dempe2 DEMPE2 Demonstrate how the ReBEL toolkit is used to train a neural network
demse1 DEMSE1 Demonstrate state estimation on a simple 2nd order LTI system.
demse2 DEMSE2 Demonstrate state estimation on a simple scalar nonlinear (time variant) problem
demse3 DEMSE3 Demonstrate nonlinear time series state estimation for Mackey-Glass chaotic time series
demse4 DEMSE4 Bearing Only Tracking Example
demse5 DEMSE4 Bearing and Frequency Tracking Example
SOURCE CODE
% ADDRELPATH  Add a relative path which gets expanded into a absolute path
%             to the front of MATLABPATH.
%
%     addrelpath(path_string)
%
%     INPUT
%            path_string        : string containing relative path
%
%
%     Example : addrelpath('../foo');
%
%     This will first expand '../foo' to an absolute path and then add it to the
%     front of MATLABPATH
%
%   See also
%   REMRELPATH
%
%   Copyright (c) Oregon Health & Science University (2006)
%
%   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
%   academic use only (see included license file) and can be obtained from
%   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
%   software should contact rebel@csee.ogi.edu for commercial licensing information.
%
%   See LICENSE (which should be part of the main toolkit distribution) for more
%   detail.
%=============================================================================================
function addrelpath(path_string)
if strncmp(computer,'PC',2),
   path_string = strrep(path_string,'/','\'); % Convert '/' to '\'
else
   path_string = strrep(path_string,'\','/'); % Convert '\' to '/'
end
current_dir = pwd;
cd(path_string);
absolute_path = pwd;
cd(current_dir);
addpath(absolute_path);