Description of consistent
Home > ReBEL-0.2.7 > core > consistent.m
consistent
PURPOSE
CONSISTENT Check ReBEL data structures for consistentency.
SYNOPSIS
function errstring = consistent(ds, type)
DESCRIPTION
 CONSISTENT   Check ReBEL data structures for consistentency.
   errstring = consistent(ds, type) checks a data structure DS of supposed TYPE for consistency.
     See also
     GSSM, GENINFDS
   Copyright (c) Oregon Health & Science University (2006)
   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
   academic use only (see included license file) and can be obtained from
   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
   software should contact rebel@csee.ogi.edu for commercial licensing information.
   See LICENSE (which should be part of the main toolkit distribution) for more
   detail.
CROSS-REFERENCE INFORMATION
This function calls:
checkstructfields CHECKSTRUCTFIELDS Checks if a data structure has the required fields.
stringmatch STRINGMATCH Returns match > 0 if string1 and string2 match (string2 can be a cell array of
This function is called by:
convgausns CONVGAUSNS Convert Gaussian noise source from one cov_type to another
fixinfds FIXINFDS Fix a user generated ("hand rolled") inference data structure to make sure it meets
geninfds GENINFDS Generate inference data structure from a generalized state space model and user defined inference parameters.
gensysnoiseds GENSYSNOISEDS Generate process and observation noise data structures for a given InferenceDS data structure
gssm GSSM Template file for generalized state space model.
gssm_bft GSSM_BFT General state space model for Bearings and Frequency Tracking of a randomly maneuvering
gssm_bot GSSM_BOT General state space model for Bearings-Only Tracking of a randomly maneuvering
gssm_brt GSSM_BRT General state space model for Bearing-and-Range Tracking of a randomly maneuvering
gssm_lti1 GSSM_LTI1 Generalized state space model for simple LTI system
gssm_mackey_glass GSSM_MACKEY_GLASS Generalized state space model for Mackey-Glass chaotic time series
gssm_n1 GSSM_N1 Generalized state space model for simple nonlinear system
gssm_speech_linear GSSM_SPEECH Generalized state space model for single phoneme speech enhancement
SOURCE CODE
function errstring = consistent(ds, type)
% CONSISTENT   Check ReBEL data structures for consistentency.
%
%   errstring = consistent(ds, type) checks a data structure DS of supposed TYPE for consistency.
%
%     See also
%     GSSM, GENINFDS
%
%   Copyright (c) Oregon Health & Science University (2006)
%
%   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
%   academic use only (see included license file) and can be obtained from
%   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
%   software should contact rebel@csee.ogi.edu for commercial licensing information.
%
%   See LICENSE (which should be part of the main toolkit distribution) for more
%   detail.
%===============================================================================================
if (nargin~=2)
  error('Not enough input arguments!');
end
if ~ischar(type)
  error('Type argument should be a string.');
end
% Assume that all is OK as default
errhead = ['  [ consistent(' inputname(1) ',''' type ''') ]   '];
errstring = '';
if ~isstruct(ds)
  errstring = [errhead inputname(1) ' is not a data structure.'];
  return
end
switch (type)
%===============================================================================================================================
%== General State Space Model Data Structure (GSSM)
%===============================================================================================================================
case 'gssm'
  %-- Check existence of required data structure fields
  mf = checkstructfields(ds,'type','tag','statedim','obsdim','paramdim','U1dim','U2dim','Vdim','Ndim','pNoise','oNoise','params','ffun','hfun','setparams');
  if ~isempty(mf), errstring = [errhead ' Data structure does not contain the following fields : ' mf]; return; end
  %-- Check type field
  if ~ischar(ds.type) | ~stringmatch(ds.type,'gssm')
      errstring = [errhead  ' Data structure is not of type ''' type ''' or the type field is not a string'];
      return;
  end
%===============================================================================================================================
%== Inference Data Structure (InferenceDS)
%===============================================================================================================================
case 'InferenceDS'
  %-- Check existence of required data structure fields
  mf = checkstructfields(ds,'type','inftype','statedim','obsdim','U1dim','U2dim','Vdim','Ndim', ...
                            'ffun','hfun','innovation','stateAngleCompIdxVec','obsAngleCompIdxVec');
  if ~isempty(mf), errstring = [errhead ' Data structure does not contain the following fields : ' mf]; return; end
  %-- Check type field
  if (~ischar(ds.type) | ~stringmatch(ds.type,'InferenceDS'))
    errstring = [errhead  ' Data structure is not of type ''' type ''' or the type field is not a string.'];
    return;
  end
  %-- Check inference type field
  if ~stringmatch(ds.inftype,{'state','parameter','joint'})
    errstring = [errhead  ' Inference type ''' type ''' unknown.'];
    return;
  end
%===============================================================================================================================
%== Noise Source Data Structure (NoiseDS)
%===============================================================================================================================
case 'NoiseDS'
  %-- Check existence of required data structure fields
  mf = checkstructfields(ds,'type','ns_type','tag','dim','sample','likelihood');
  if ~isempty(mf), errstring = [errhead ' Data structure does not contain the following fields : ' mf]; return; end
  %-- Check type field
  if (~ischar(ds.type) | ~stringmatch(ds.type,'NoiseDS'))
    errstring = [errhead  ' Data structure is not of type ''' type ''' or the type field is not a string.'];
    return;
  end
%===============================================================================================================================
otherwise
  errstring = [errhead 'Data structure type ' type ' not supported.'];
end
return