Description of cvecrep
Home > ReBEL-0.2.7 > core > cvecrep.m
cvecrep
PURPOSE
CVECREP Column vector replicate
SYNOPSIS
function m = cvecrep(v,c)
DESCRIPTION
 CVECREP  Column vector replicate
   M = cvecrep(V, C) Replicates a Nx1 dimensional column vector V, C times to generate a
   NxC dimensional matrix M.
   See also
   RVECREP, REPMAT
   Copyright (c) Oregon Health & Science University (2006)
   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
   academic use only (see included license file) and can be obtained from
   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
   software should contact rebel@csee.ogi.edu for commercial licensing information.
   See LICENSE (which should be part of the main toolkit distribution) for more
   detail.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cdkf CDKF Central Difference Kalman Filter (Sigma-Point Kalman Filter variant)
gauseval GAUSEVAL Calculates the likelihood of a dataset X under a Gaussian probability
geninfds GENINFDS Generate inference data structure from a generalized state space model and user defined inference parameters.
gennoiseds GENNOISEDS Generates a NoiseDS data structure describing a noise source.
mlpff MLPFF Calculates the output of a ReBEL feed-forward MLP neural network with 2,3 or 4 layers
mlpjacobian MLPJACOBIAN Calculates the Jacobian (first partial derivative matrix)
pf PF Generic Particle Filter
sppf SPPF Sigma-Point Particle Filter.
srcdkf SRCDKF Square Root Central Difference Kalman Filter (Sigma-Point Kalman Filter variant)
srukf SRUKF Square Root Unscented Kalman Filter (Sigma-Point Kalman Filter variant)
ukf UKF Unscented Kalman Filter
gssm_mackey_glass GSSM_MACKEY_GLASS Generalized state space model for Mackey-Glass chaotic time series
demje1 DEMJE1 Demonstrate joint estimation on a 2nd order LTI system.
dempe1 DEMPE1 Demonstrate parameter estimation on a simple 2nd order LTI system.
demse2 DEMSE2 Demonstrate state estimation on a simple scalar nonlinear (time variant) problem
demse4 DEMSE4 Bearing Only Tracking Example
demse5 DEMSE4 Bearing and Frequency Tracking Example
SOURCE CODE
function m = cvecrep(v,c)
% CVECREP  Column vector replicate
%
%   M = cvecrep(V, C) Replicates a Nx1 dimensional column vector V, C times to generate a
%   NxC dimensional matrix M.
%
%   See also
%   RVECREP, REPMAT
%   Copyright (c) Oregon Health & Science University (2006)
%
%   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
%   academic use only (see included license file) and can be obtained from
%   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
%   software should contact rebel@csee.ogi.edu for commercial licensing information.
%
%   See LICENSE (which should be part of the main toolkit distribution) for more
%   detail.
%=============================================================================================
if isempty(v)
  m = zeros(0,c);
else
  m = v(:,ones(c,1));
end