Description of geninfds
Home > ReBEL-0.2.7 > core > geninfds.m
geninfds
PURPOSE
GENINFDS Generate inference data structure from a generalized state space model and user defined inference parameters.
SYNOPSIS
function InferenceDS = geninfds(ArgDS)
DESCRIPTION
 GENINFDS  Generate inference data structure from a generalized state space model and user defined inference parameters.
   InferenceDS = geninfds(ArgDS)
   This function generates a ReBEL inference data structure from a generalized state space model (gssm) data
   structure. This inference data structure is used by all ReBEL estimation algorithms. All the parameters and
   information needed to build the data structures are passed into the function by means of a user defined argument
   data structure, ArgDS. The specifics of the input and output parameters are given
   below.
   INPUT ARGUMENT DATA STRUCTURE FIELDS  : ArgDS._______
     .type               : (string)      Inference (estimation) type : 'state', 'parameter' or 'joint'
     .tag                : (string)      Arbitrary user defined ID tag string
     .model              : (gssm)        Generalized state space model descriptor (see gssm.m)
     .paramParamIdxVec   : (r-vector)   <<OPTIONAL for parameter and joint estimation, not used by state estimation>>
                                         Index vector containing indices of a subset of parameters which must be
                                         estimated. Default (if ommitted) is to estimate all parameters.
     .paramFunSelect     : (string)     <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
                                         String indicating which of the state-transition 'ffun' or state-observation
                                         'hfun' functions should be used as the functional unit for parameter estimation.
                                         The default value for this field (if ommitted) is 'both' which uses both functions,
                                         i.e. obs=hfun(ffun(x)). One can also specify 'both-p' which uses both functions
                                         in a parallel combination, i.e. obs = [ffun(x)]
                                                                               [hfun(x)]
     .paramFFunOutIdxVec : (r-vector)   <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
                                         Index vector containing indices of a subset of the output of FFUN which must be
                                         used for parameter estimation observations. This argument is only used if
                                         .paramFunSelect = 'both' or 'ffun'. The default is to use all FFUN outputs.
     .paramHFunOutIdxVec : (r-vector)   <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
                                         Index vector containing indices of a subset of the output of HFUN which must be
                                         used for parameter estimation observations. This argument is only used if
                                         .paramFunSelect = 'both' or 'hfun'. The default is to use all HFUN outputs.
   OUTPUT ARGUMENTS
     InferenceDS         : inference data structure
     See also
     GSSM, GENNOISEDS, GENSYSNOISEDS, CONSIST
   Copyright (c) Oregon Health & Science University (2006)
   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
   academic use only (see included license file) and can be obtained from
   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
   software should contact rebel@csee.ogi.edu for commercial licensing information.
   See LICENSE (which should be part of the main toolkit distribution) for more
   detail.
CROSS-REFERENCE INFORMATION
This function calls:
checkdups CHECKDUPS Checks for the presence of duplicate entries in an array
checkstructfields CHECKSTRUCTFIELDS Checks if a data structure has the required fields.
consistent CONSISTENT Check ReBEL data structures for consistentency.
cvecrep CVECREP Column vector replicate
stringmatch STRINGMATCH Returns match > 0 if string1 and string2 match (string2 can be a cell array of
This function is called by:
demspeech_dual DEMSPEECH_DUAL Sigma-Point Kalman Filter based Speech Enhancement Demonstration.
demje1 DEMJE1 Demonstrate joint estimation on a 2nd order LTI system.
demje2 DEMJE2 Demonstrate nonlinear time series joint estimation for Mackey-Glass chaotic time series
dempe1 DEMPE1 Demonstrate parameter estimation on a simple 2nd order LTI system.
demse1 DEMSE1 Demonstrate state estimation on a simple 2nd order LTI system.
demse2 DEMSE2 Demonstrate state estimation on a simple scalar nonlinear (time variant) problem
demse3 DEMSE3 Demonstrate nonlinear time series state estimation for Mackey-Glass chaotic time series
demse4 DEMSE4 Bearing Only Tracking Example
demse5 DEMSE4 Bearing and Frequency Tracking Example
SUBFUNCTIONS
function new_state = ffun_state(InferenceDS, state, V, U1)
function observ = hfun_state(InferenceDS, state, N, U2)
function tran_prior = prior_state(InferenceDS, nextstate, state, U1, pNoiseDS)
function llh = likelihood_state(InferenceDS, obs, state, U2, oNoiseDS)
function innov = innovation_state(InferenceDS, obs, observ)
function varargout = linearize_state(InferenceDS, state, V, N, U1, U2, varargin)
function new_state = ffun_parameter(InferenceDS, state, V, U1)
function tran_prior = prior_parameter(InferenceDS, nextstate, state, U1, pNoiseDS)
function observ = hfun_parameter_bothp(InferenceDS, state, N, U2)
function innov = innovation_parameter_bothp(InferenceDS, obs, observ)
function llh = likelihood_parameter_bothp(InferenceDS, obs, state, U2, oNoiseDS)
function observ = hfun_parameter_f(InferenceDS, state, N, U2)
function observ = hfun_parameter_h(InferenceDS, state, N, U2)
function observ = hfun_parameter_both(InferenceDS, state, N, U2)
function llh = likelihood_parameter_f(InferenceDS, obs, state, U2, oNoiseDS)
function llh = likelihood_parameter_h(InferenceDS, obs, state, U2, oNoiseDS)
function llh = likelihood_parameter_both(InferenceDS, obs, state, U2, oNoiseDS)
function varargout = linearize_parameter_both(InferenceDS, state, V, N, U1, U2, varargin)
function varargout = linearize_parameter_bothp(InferenceDS, state, V, N, U1, U2, varargin)
function varargout = linearize_parameter_f(InferenceDS, state, V, N, U1, U2, varargin)
function varargout = linearize_parameter_h(InferenceDS, state, V, N, U1, U2, varargin)
function new_state = ffun_joint(InferenceDS, state, V, U1)
function tran_prior = prior_joint(InferenceDS, nextstate, state, U1, pNoiseDS)
function observ = hfun_joint(InferenceDS, state, N, U2)
function llh = likelihood_joint(InferenceDS, obs, state, U2, oNoiseDS)
function varargout = linearize_joint(InferenceDS, state, V, N, U1, U2, varargin)
function innov = innovation_generic(InferenceDS, obs, observ)
function varargout = linearize_generic(InferenceDS, state, V, N, U1, U2, varargin)
SOURCE CODE
function InferenceDS = geninfds(ArgDS)
% GENINFDS  Generate inference data structure from a generalized state space model and user defined inference parameters.
%
%   InferenceDS = geninfds(ArgDS)
%
%   This function generates a ReBEL inference data structure from a generalized state space model (gssm) data
%   structure. This inference data structure is used by all ReBEL estimation algorithms. All the parameters and
%   information needed to build the data structures are passed into the function by means of a user defined argument
%   data structure, ArgDS. The specifics of the input and output parameters are given
%   below.
%
%   INPUT ARGUMENT DATA STRUCTURE FIELDS  : ArgDS._______
%
%     .type               : (string)      Inference (estimation) type : 'state', 'parameter' or 'joint'
%     .tag                : (string)      Arbitrary user defined ID tag string
%     .model              : (gssm)        Generalized state space model descriptor (see gssm.m)
%
%     .paramParamIdxVec   : (r-vector)   <<OPTIONAL for parameter and joint estimation, not used by state estimation>>
%                                         Index vector containing indices of a subset of parameters which must be
%                                         estimated. Default (if ommitted) is to estimate all parameters.
%     .paramFunSelect     : (string)     <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
%                                         String indicating which of the state-transition 'ffun' or state-observation
%                                         'hfun' functions should be used as the functional unit for parameter estimation.
%                                         The default value for this field (if ommitted) is 'both' which uses both functions,
%                                         i.e. obs=hfun(ffun(x)). One can also specify 'both-p' which uses both functions
%                                         in a parallel combination, i.e. obs = [ffun(x)]
%                                                                               [hfun(x)]
%     .paramFFunOutIdxVec : (r-vector)   <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
%                                         Index vector containing indices of a subset of the output of FFUN which must be
%                                         used for parameter estimation observations. This argument is only used if
%                                         .paramFunSelect = 'both' or 'ffun'. The default is to use all FFUN outputs.
%     .paramHFunOutIdxVec : (r-vector)   <<OPTIONAL for parameter estimation, not used by state and joint estimation>>
%                                         Index vector containing indices of a subset of the output of HFUN which must be
%                                         used for parameter estimation observations. This argument is only used if
%                                         .paramFunSelect = 'both' or 'hfun'. The default is to use all HFUN outputs.
%
%
%   OUTPUT ARGUMENTS
%
%     InferenceDS         : inference data structure
%
%     See also
%     GSSM, GENNOISEDS, GENSYSNOISEDS, CONSIST
%
%   Copyright (c) Oregon Health & Science University (2006)
%
%   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
%   academic use only (see included license file) and can be obtained from
%   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
%   software should contact rebel@csee.ogi.edu for commercial licensing information.
%
%   See LICENSE (which should be part of the main toolkit distribution) for more
%   detail.
%========================================================================================================
%--- ERROR CHECKING -------------------------------------------------------------------------------------
if (nargin < 1)
    error(' [ geninfds ] Not enough inputs.');
end
if ~isstruct(ArgDS)
    error(' [ geninfds ] Input argument must be an argument data structure ArgDS.');
end
mf = checkstructfields(ArgDS,'type','model');  % Check existence of required data structure fields
if ~isempty(mf)
    error([' [ geninfds ] Argument data structure does not contain the following required fields : ' mf]);
end
if ~ischar(ArgDS.type)
    error(' [ geninfds ] ArgDS.type must be a string indicating the inference type, i.e. ''state'', ''parameter'' or ''joint''.');
end
%--- BUILD INFERENCE DATA STRUCTURE ----------------------------------------------------------------------
InferenceDS.type    = 'InferenceDS';   % data structure type
InferenceDS.inftype = ArgDS.type;      % inference type
if isfield(ArgDS,'tag'),
    InferenceDS.tag  = ArgDS.tag;                         % ID tag
else
    InferenceDS.tag  = '';
end
if ~isempty(consistent(ArgDS.model,'gssm'));                 % check for consistentency of GSSM data structure
    error([' [ geninfds ] There is an inconsistentency with the supplied GSSM data structure subfield. Please use ' ...
           'the CONSIST function on the GSSM model to determine the exact problem.']);
else
    model = ArgDS.model;
    InferenceDS.model = model;                            % embed GSSM model
end
switch ArgDS.type
    %---
    %--- STATE ESTIMATION  --------------------------------------------------------------------------------
    %---
    case 'state'
        %--- dimensions & other detail ---
        InferenceDS.statedim = model.statedim;                % state dimension
        InferenceDS.obsdim   = model.obsdim;                  % observation dimension
        InferenceDS.U1dim    = model.U1dim;                   % exogenous input 1 dimension
        InferenceDS.U2dim    = model.U2dim;                   % exogenous input 2 dimension
        InferenceDS.Vdim = model.pNoise.dim;                  % process noise dimension
        InferenceDS.Ndim = model.oNoise.dim;                  % observation noise dimension
        %--- function handles ---
        InferenceDS.ffun = @ffun_state;
        InferenceDS.hfun = @hfun_state;
        if isfield(model, 'prior'),
            InferenceDS.prior = @prior_state;
        end
        if isfield(model,'likelihood'),
            InferenceDS.likelihood = @likelihood_state;
        end
        if isfield(model,'innovation'),
            InferenceDS.innovation = @innovation_state;
        else
            InferenceDS.innovation = [];
        end
        if isfield(model,'linearize'),
            InferenceDS.linearize = @linearize_state;             % linearization function functionhandle
        else
            InferenceDS.linearize = @linearize_generic;           % generic (perturbation based linearization)
        end
        %--- other stuff ---
        % Index vectors indicating the presence of angular components in the state and observation vectors
        if isfield(model,'stateAngleCompIdxVec'),
            InferenceDS.stateAngleCompIdxVec = model.stateAngleCompIdxVec;
        else
            InferenceDS.stateAngleCompIdxVec = [];
        end
        if isfield(model,'obsAngleCompIdxVec'),
            InferenceDS.obsAngleCompIdxVec = model.obsAngleCompIdxVec;
        else
            InferenceDS.obsAngleCompIdxVec = [];
        end
    %---
    %--- PARAMETER ESTIMATION ----------------------------------------------------------------------------
    %---
    case 'parameter'
        % Check parameter index vector
        if ~isfield(ArgDS,'paramParamIdxVec')
            paramParamIdxVec = 1:model.paramdim;
        else
            paramParamIdxVec = ArgDS.paramParamIdxVec;
            % Check vector entries
            if ((max(paramParamIdxVec) > model.paramdim) | (min(paramParamIdxVec) < 1))
                error(' [ geninfds::parameter ] Parameter index vector has illegal entries');
            end
            % Check for duplicate index entries
            if checkdups(paramParamIdxVec)
                error(' [ geninfds::parameter ] Duplicate parameter index vector entries not allowed.');
            end
        end
        InferenceDS.paramParamIdxVec = paramParamIdxVec;                      % copy index vector in InferenceDS
        % Check parameter function select argument
        if ~isfield(ArgDS,'paramFunSelect')
            paramFunSelect = 'both';
        elseif stringmatch(ArgDS.paramFunSelect,{'ffun','hfun','both-p','both'})
            paramFunSelect = ArgDS.paramFunSelect;
        else
            error(' [ geninfds::parameter ] Unknown value used for paramFunSelect');
        end
        InferenceDS.paramFunSelect = paramFunSelect;                          % copy parameter function select string
        % Check ffun and hfun output index vectors
        if stringmatch(paramFunSelect,{'both-p','ffun'})
            if ~isfield(ArgDS,'paramFFunOutIdxVec')
                paramFFunOutIdxVec = 1:model.statedim;
            else
                paramFFunOutIdxVec = ArgDS.paramFFunOutIdxVec;
                % Check vector entries
                if ((max(paramFFunOutIdxVec) > model.statedim) | (min(paramFFunOutIdxVec) < 1))
                    error(' [ geninfds::parameter ] FFUN output index vector has illegal entries');
                end
                % Check for duplicate index entries
                if checkdups(paramFFunOutIdxVec)
                    error(' [ geninfds::parameter ] Duplicate FFUN output index vector entries not allowed.');
                end
            end
            InferenceDS.paramFFunOutIdxVec = paramFFunOutIdxVec;                  % copy ffun output
        end
        if stringmatch(paramFunSelect,{'both','hfun','both-p'})
            if ~isfield(ArgDS,'paramHFunOutIdxVec')
                paramHFunOutIdxVec = 1:model.obsdim;
            else
                paramHFunOutIdxVec = ArgDS.paramHFunOutIdxVec;
                % Check vector entries
                if ((max(paramHFunOutIdxVec) > model.obsdim) | (min(paramHFunOutIdxVec) < 1))
                    error(' [ geninfds::parameter ] HFUN output index vector has illegal entries');
                end
                % Check for duplicate index entries
                if checkdups(paramHFunIdxVec)
                    error(' [ geninfds::parameter ] Duplicate HFUN output index vector entries not allowed.');
                end
            end
            InferenceDS.paramHFunOutIdxVec = paramHFunOutIdxVec;                  % copy ffun output
        end
        %-- Setup rest of structure
        switch paramFunSelect
        %...................................................................................................................
        case 'both'
            %--- dimensions & other detail ---
            InferenceDS.statedim = length(paramParamIdxVec);                 % state dimension
            InferenceDS.obsdim = length(paramHFunOutIdxVec);                 % observation dimension
            InferenceDS.U1dim = 0;                                           % expgenous input 1 dimension
            InferenceDS.U2dim = model.U1dim + model.statedim + model.U2dim;  % exogenous input 2 dimension
            InferenceDS.Vdim = InferenceDS.statedim;                         % process noise dimension
            InferenceDS.Ndim = model.Vdim + model.Ndim;                      % observation noise dimension
            %--- functions ---
            InferenceDS.ffun = @ffun_parameter;                             % state transition function functionhandle
            InferenceDS.hfun = @hfun_parameter_both;                        % state observation function functionhandle
            if isfield(model,'linearize')
                InferenceDS.linearize = @linearize_parameter_both;          % linearization function functionhandle
            else
                InferenceDS.linearize = @linearize_generic;
            end
            InferenceDS.prior = @prior_parameter;
            if isfield(model,'likelihood'),
                InferenceDS.likelihood = @likelihood_parameter_both;
            end
            if isfield(model,'innovation'),
                InferenceDS.innovation = @innovation_state;
            else
                InferenceDS.innovation = [];
            end
            %--- copy/setup fixed linear model parameters ---
            InferenceDS.A = eye(InferenceDS.statedim);
            InferenceDS.B = [];
            InferenceDS.G = eye(InferenceDS.statedim);
            %--- other stuff ---
            % Index vectors indicating the presence of angular components in the state and observation vectors
            InferenceDS.stateAngleCompIdxVec = [];
            InferenceDS.obsAngleCompIdxVec = [];
            if isfield(model,'obsAngleCompIdxVec'),
               for k=1:length(model.obsAngleCompIdxVec),
                 idx = find(InferenceDS.paramHFunOutIdxVec == model.obsAngleCompIdxVec(k));
                 InferenceDS.obsAngleCompIdxVec = [InferenceDS.obsAngleCompIdxVec idx];
               end
            end
        %...................................................................................................................
        case 'both-p'
            %--- dimensions & other detail ---
            InferenceDS.statedim = length(paramParamIdxVec);                        % state dimension
            InferenceDS.obsdim = length(paramFFunOutIdxVec) + length(paramHFunOutIdxVec); % observation dimension
            InferenceDS.U1dim = 0;                                                  % exogenous input 1 dimension
            InferenceDS.U2dim = model.U1dim + 2*model.statedim + model.U2dim;       % exogenous input 2 dimension
            InferenceDS.Vdim = InferenceDS.statedim;                                % process noise dimension
            InferenceDS.Ndim = model.Vdim+model.Ndim;                               % observation noise dimension
            %--- functions ---
            InferenceDS.ffun = @ffun_parameter;                               % state transition function functionhandle
            InferenceDS.hfun = @hfun_parameter_bothp;                         % state observation function functionhandle
            if isfield(model,'linearize')
                InferenceDS.linearize = @linearize_parameter_bothp;           % linearization function functionhandle
            else
                InferenceDS.linearize = @linearize_generic;
            end
            InferenceDS.prior = @prior_parameter;
            if (isfield(model,'likelihood') & isfield(model,'prior')),
                InferenceDS.likelihood = @likelihood_parameter_bothp;
            end
            InferenceDS.innovation = [];
            %--- copy/setup fixed linear model parameters ---
            InferenceDS.A = eye(InferenceDS.statedim);
            InferenceDS.B = [];
            InferenceDS.G = eye(InferenceDS.statedim);
            %--- other stuff ---
            % Index vectors indicating the presence of angular components in the state and observation vectors
            InferenceDS.stateAngleCompIdxVec = [];
            InferenceDS.obsAngleCompIdxVec = [];
            if isfield(model,'stateAngleCompIdxVec'),
               for k=1:length(model.stateAngleCompIdxVec),
                 idx = find(InferenceDS.paramFFunOutIdxVec == model.stateAngleCompIdxVec(k));
                 InferenceDS.obsAngleCompIdxVec = [InferenceDS.obsAngleCompIdxVec idx];
               end
            end
            if isfield(model,'obsAngleCompIdxVec'),
               for k=1:length(model.obsAngleCompIdxVec),
                 idx = find(InferenceDS.paramHFunOutIdxVec == model.obsAngleCompIdxVec(k));
                 InferenceDS.obsAngleCompIdxVec = [InferenceDS.obsAngleCompIdxVec idx];
               end
            end
        %...................................................................................................................
        case 'ffun'
            %--- parameter dimensions ---
            InferenceDS.statedim = length(paramParamIdxVec);                  % state dimension
            InferenceDS.obsdim = length(paramFFunOutIdxVec);                  % observation dimension
            InferenceDS.U1dim = 0;                                            % exogenous input 1 dimension
            InferenceDS.U2dim = model.U1dim + model.statedim;                 % exogenous input 2 dimension
            InferenceDS.Vdim = InferenceDS.statedim;                          % process noise dimension
            InferenceDS.Ndim = model.Vdim;                                    % observation noise dimension
            %--- functions ---
            InferenceDS.ffun = @ffun_parameter;                               % state transition function functionhandle
            InferenceDS.hfun = @hfun_parameter_f;                             % state observation function functionhandle
            if isfield(model,'linearize')
                InferenceDS.linearize = @linearize_parameter_f;               % linearization function functionhandle
            else
                InferenceDS.linearize = @linearize_generic;
            end
            InferenceDS.prior = @prior_parameter;
            if isfield(model,'prior'),
                InferenceDS.likelihood = @likelihood_parameter_f;
            end
            InferenceDS.innovation = [];
            %--- copy/setup fixed linear model parameters ---
            InferenceDS.A         = eye(InferenceDS.statedim);
            InferenceDS.B         = [];
            InferenceDS.G         = eye(InferenceDS.statedim);
            %--- other stuff ---
            % Index vectors indicating the presence of angular components in the state and observation vectors
            InferenceDS.stateAngleCompIdxVec = [];
            InferenceDS.obsAngleCompIdxVec = [];
            if isfield(model,'stateAngleCompIdxVec'),
               for k=1:length(model.stateAngleCompIdxVec),
                 idx = find(InferenceDS.paramFFunOutIdxVec == model.stateAngleCompIdxVec(k));
                 InferenceDS.obsAngleCompIdxVec = [InferenceDS.obsAngleCompIdxVec idx];
               end
            end
        %...................................................................................................................
        case 'hfun'
            %--- parameter dimensions ---
            InferenceDS.statedim = length(paramParamIdxVec);                  % state dimension
            InferenceDS.obsdim = length(paramHFunOutIdxVec);                  % observation dimension
            InferenceDS.U1dim = 0;                                            % exogenous input 1 dimension
            InferenceDS.U2dim = model.U2dim + model.statedim;                 % exogenous input 2 dimension
            InferenceDS.Vdim = InferenceDS.statedim;                          % process noise dimension
            InferenceDS.Ndim = model.Ndim;                                    % observation noise dimension
            %--- functions ---
            InferenceDS.ffun      = @ffun_parameter;                          % state transition function functionhandle
            InferenceDS.hfun      = @hfun_parameter_h;                        % state observation function functionhandle
            if isfield(model,'linearize')
                InferenceDS.linearize = @linearize_parameter_h;               % linearization function functionhandle
            else
                InferenceDS.linearize = @linearize_generic;
            end
            InferenceDS.prior = @prior_parameter;
            if isfield(model,'likelihood'),
                InferenceDS.likelihood = @likelihood_parameter_h;
            end
            InferenceDS.innovation = [];
            %--- copy/setup fixed linear model parameters ---
            InferenceDS.A         = eye(InferenceDS.statedim);
            InferenceDS.B         = [];
            InferenceDS.G         = eye(InferenceDS.statedim);
            %--- other stuff ---
            % Index vectors indicating the presence of angular components in the state and observation vectors
            InferenceDS.stateAngleCompIdxVec = [];
            InferenceDS.obsAngleCompIdxVec = [];
            if isfield(model,'obsAngleCompIdxVec'),
               for k=1:length(model.obsAngleCompIdxVec),
                 idx = find(InferenceDS.paramHFunOutIdxVec == model.obsAngleCompIdxVec(k));
                 InferenceDS.obsAngleCompIdxVec = [InferenceDS.obsAngleCompIdxVec idx];
               end
            end
        otherwise
            error(' The only valid values for the funselect field are : ''both'' , ''ffun'' and ''hfun''.');
        end
    %---
    %--- JOINT ESTIMATION --------------------------------------------------------------------------------
    %---
    case 'joint'
        % Check parameter index vector
        if ~isfield(ArgDS,'paramParamIdxVec')
            paramParamIdxVec = 1:model.paramdim;
        else
            paramParamIdxVec = ArgDS.paramParamIdxVec;
            % Check vector entries
            if ((max(paramParamIdxVec) > model.paramdim) | (min(paramParamIdxVec) < 1))
                error(' [ geninfds::parameter ] Parameter index vector has illegal entries');
            end
            % Check for duplicate index entries
            if checkdups(paramParamIdxVec)
                error(' [ geninfds::parameter ] Duplicate parameter index vector entries not allowed.');
            end
        end
        InferenceDS.paramParamIdxVec = paramParamIdxVec;                  % copy index vector in InferenceDS
        %--- dimensions ---
        pdim = length(paramParamIdxVec);
        InferenceDS.paramParamIdxVec = paramParamIdxVec;                  % save index vector in InferenceDS
        InferenceDS.statedim  = model.statedim + pdim;                    % state dimension
        InferenceDS.obsdim    = model.obsdim;                             % observation dimension
        InferenceDS.U1dim     = model.U1dim;                              % exogenous input 1 dimension
        InferenceDS.U2dim     = model.U2dim;                              % exogenous input 2 dimension
        InferenceDS.Vdim      = model.Vdim + pdim;                        % process noise dimension
        InferenceDS.Ndim      = model.Ndim;                               % observation noise dimension
        %--- functions ---
        InferenceDS.ffun      = @ffun_joint;                              % state transition function functionhandle
        InferenceDS.hfun      = @hfun_joint;                              % state observation function functionhandle
        if isfield(model, 'prior'),
            InferenceDS.prior = @prior_joint;
        end
        if isfield(model, 'likelihood')
            InferenceDS.likelihood = @likelihood_joint;
        end
        if isfield(model, 'innovation')
            InferenceDS.innovation = @innovation_state;
        else
            InferenceDS.innovation = [];
        end
        if isfield(model, 'linearize')
            InferenceDS.linearize = @linearize_joint;                     % linearization function functionhandle
        else
            InferenceDS.linearize = @linearize_generic;
        end
        %--- other stuff ---
        % Index vectors indicating the presence of angular components in the state and observation vectors
        if isfield(model,'stateAngleCompIdxVec'),
            InferenceDS.stateAngleCompIdxVec = model.stateAngleCompIdxVec;
        else
            InferenceDS.stateAngleCompIdxVec = [];
        end
        if isfield(model,'obsAngleCompIdxVec'),
            InferenceDS.obsAngleCompIdxVec = model.obsAngleCompIdxVec;
        else
            InferenceDS.obsAngleCompIdxVec = [];
        end
%-----------------------------------------------------------------------------------------------------------------------------------------------
otherwise
  error([' [ geninfds ] Inference type ''' ArgDS.type ''' not supported.']);
end
% add misc. default data fields
InferenceDS.uType = 'TMU';             % Update type : Time-and-Measurement Update is the default
                                       % Other options are : TU - time update only or MU - measurement update only.
return;
%***********************************************************************************************
%***                                                                                         ***
%***                               SUB FUNCTION BLOCK                                        ***
%***                                                                                         ***
%***********************************************************************************************
%===============================================================================================
%================================== STATE ESTIMATION FUNCTIONS =================================
function new_state = ffun_state(InferenceDS, state, V, U1)
    %  FFUN_STATE  State transition function of meta system for state estimation
    %
    %    new_state = ffun_state(InferenceDS, state, V, U1)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system state vector
    %         V               : (c-vector) meta system process noise vector
    %         U1              : (c-vector) meta system exogenous input 1
    %    OUTPUT
    %         new_state       : (c-vector) updated meta system state vector
    new_state = InferenceDS.model.ffun( InferenceDS.model, state, V, U1);
%-------------------------------------------------------------------------------------
function observ = hfun_state(InferenceDS, state, N, U2)
    %  HFUN_STATE  State observation function of meta system for state estimation
    %
    %    observ = hfun_state(InferenceDS, state, N, U2)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system state vector
    %         N               : (c-vector) meta system observation noise vector
    %         U2              : (c-vector) meta system exogenous input 2
    %    OUTPUT
    %         observ          : (c-vector)  meta system observation vector
    observ = InferenceDS.model.hfun( InferenceDS.model, state, N, U2);
%-------------------------------------------------------------------------------------
function tran_prior = prior_state(InferenceDS, nextstate, state, U1, pNoiseDS)
    %  PRIOR_STATE  Calculates the transition prior probability P(x_k|x_(k-1))
    %
    %    tranprior = prior_state(InferenceDS, nextstate, state, pNoiseDS)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         nextstate       : (c-vector)  system state at time k
    %         state           : (c-vector)  system state at time k-1
    %         U1              : (c-vector) meta system exogenous input 1
    %         pNoiseDS        : (NoiseDS)   process noise data structure
    %    OUTPUT
    %         tranprior       : scalar probability P(x_k|x_(k-1))
    tran_prior = InferenceDS.model.prior( InferenceDS.model, nextstate, state, U1, pNoiseDS);
%-------------------------------------------------------------------------------------
function llh = likelihood_state(InferenceDS, obs, state, U2, oNoiseDS)
    %  LIKELIHOOD_STATE  Calculates the likelood of a real-world observation obs given
    %                    a realization of the predicted observation for a given state,
    %                    i.e. p(y|x) = p(obs|state)
    %
    %    llh = likelihood_state(InferenceDS, obs, observ)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         obs             : (c-vector)  real-world observation vector
    %         state           : (c-vector)  meta system state vector
    %         U2              : (c-vector) meta system exogenous input 2
    %         oNoiseDS        : (NoiseDS)   observation noise data structure
    %    OUTPUT
    %         llh             : scalar  likelihood
    llh = InferenceDS.model.likelihood( InferenceDS.model, obs, state, U2, oNoiseDS);
%-------------------------------------------------------------------------------------
function innov = innovation_state(InferenceDS, obs, observ)
    %  INNOVATION_STATE  Calculates the innovation signal (difference) between the
    %   output of HFUN, i.e. OBSERV (the predicted system observation) and an actual
    %   'real world' observation OBS. This function might be as simple as
    %   INNOV = OBS - OBSERV, which is the default case, but can also be more
    %   complex for complex measurement processes where for example multiple (possibly false)
    %   observations can be observed for a given hidden ground truth.
    %
    %    innov = innovation_state(InferenceDS, obs, observ)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         obs             : (c-vector)  real-world observation vector
    %         observ          : (c-vector)  meta system observation vector
    %    OUTPUT
    %         inov            : (c-vector) innovation sequence
    innov = InferenceDS.model.innovation( InferenceDS.model, obs, observ);
%-------------------------------------------------------------------------------------
function varargout = linearize_state(InferenceDS, state, V, N, U1, U2, varargin)
    %  LINEARIZE_STATE  Linearization function of meta system for state estimation
    %
    %    varargout = linearize_state(InferenceDS, state, V, N, U1, U2, varargin)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system state vector
    %         V               : (c-vector) meta system process noise vector
    %         N               : (c-vector) meta system observation noise vector
    %         U1              : (c-vector) meta system exogenous input 1
    %         U2              : (c-vector) meta system exogenous input 2
    %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
    %    OUTPUT
    %         varargout       : (matrices) linearization terms corresponding with varargin strings
  nop = length(varargin);
  for k=1:nop,
    varargout{k} = InferenceDS.model.linearize( InferenceDS.model, state, V, N, U1, U2, varargin{k});
  end
%===========================================================================================================
%================================ PARAMETER ESTIMATION FUNCTIONS ===========================================
function new_state = ffun_parameter(InferenceDS, state, V, U1)
    %  FFUN_PARAMETER  State transition function of meta system for parameter estimation
    %
    %    new_state = ffun_parameter(InferenceDS, state, V, U1)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system system state vector
    %         V               : (c-vector) meta system process noise vector
    %         U1              : (c-vector) meta system exogenous input 1
    %    OUTPUT
    %         new_state       : (c-vector) updated meta system state vector
    %
    % Relationship between input arguments and external model (GSSM) variables
    %
    %   state -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof.
    %   U1    -> this is usually an empty matrix
    %   V     -> synthetic process noise (speeds up convergence)
    %
    new_state = state + V;
%-------------------------------------------------------------------------------------
function tran_prior = prior_parameter(InferenceDS, nextstate, state, U1, pNoiseDS)
    %  PRIOR_STATE  Calculates the transition prior probability P(x_k|x_(k-1))
    %
    %    tranprior = prior_parameter(InferenceDS, nextstate, state, pNoiseDS)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         nextstate       : (c-vector)  system state at time k
    %         state           : (c-vector)  system state at time k-1
    %         U1              : (c-vector) meta system exogenous input 1
    %         pNoiseDS        : (NoiseDS)   process noise data structure
    %    OUTPUT
    %         tranprior       : scalar probability P(x_k|x_(k-1))
    X = nextstate - state;
    tran_prior = pNoiseDS.likelihood( pNoiseDS, X);
%-------------------------------------------------------------------------------------
function observ = hfun_parameter_bothp(InferenceDS, state, N, U2)
    %  HFUN_PARAMETER_BOTHP  State observation function of meta system for parameter estimation using both ffun and hfun
    %                     from the underlying GSSM.
    %
    %    observ = hfun_parameter_bothp(InferenceDS, state, N, U2)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system state vector
    %         N               : (c-vector) meta system observation noise vector
    %         U2              : (c-vector) meta system exogenous input 2
    %    OUTPUT
    %         observ          : (c-vector) meta system observation vector
    %
    % Relationship arguments and external model (GSSM) variables
    %
    %   state  -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
    %   U2     -> [external_state(k-1) external_U1(k-1) external_state(k) external_U2(k)]'
    %   N      -> [external_process_noise(k-1) external_observation_noise(k)]'
    %   observ -> [external_state(k) external_observation(k)]'
    [dim,nov] = size(state);
    observ = zeros(InferenceDS.obsdim,nov);
    dimX  = InferenceDS.model.statedim;
%    dimO  = InferenceDS.model.obsdim;
    dimV  = InferenceDS.model.Vdim;
    dimN  = InferenceDS.model.Ndim;
    dimU1 = InferenceDS.model.U1dim;
%    dimU2 = InferenceDS.model.U2dim;
    ext_state_1     = U2(1:dimX,:);
    ext_proc_noise  = N(1:dimV,:);
    ext_U1          = U2(dimX+1:dimX+dimU1,:);
    ext_state_2     = U2(dimX+dimU1+1:dimX+dimU1+dimX,:);
    ext_obs_noise   = N(dimV+1:dimV+dimN,:);
    ext_U2          = U2(dimX+dimU1+dimX+1:end,:);
    ffun_idx = InferenceDS.paramFFunOutIdxVec;
    hfun_idx = InferenceDS.paramHFunOutIdxVec;
    dimF0 = length(ffun_idx);
    dimH0 = length(hfun_idx);
    % loop over all input vectors
    for k=1:nov,
        % set model parameter vector
        InferenceDS.model = InferenceDS.model.setparams( InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
        % FFUN part of observation
        FFunOut = InferenceDS.model.ffun( InferenceDS.model, ext_state_1(:,k), ext_proc_noise(:,k), ext_U1(:,k));
        % HFUN part of observation
        HFunOut = InferenceDS.model.hfun( InferenceDS.model, ext_state_2(:,k), ext_obs_noise(:,k), ext_U2(:,k));
        observ(1:dimF0,k) = FFunOut(ffun_idx);
        observ(dimF0+1:dimF0+dimH0,k) = HFunOut(hfun_idx);
    end
%-------------------------------------------------------------------------------------
function innov = innovation_parameter_bothp(InferenceDS, obs, observ)
    %  INNOVATION_PARAMETER_BOTHP  Calculates the innovation signal (difference) between the
    %   output of HFUN, i.e. OBSERV (the predicted system observation) and an actual
    %   'real world' observation OBS.
    %
    %    innov = innovation_parameter_bothp(InferenceDS, obs, observ)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         obs             : (c-vector)  real-world observation vector
    %         observ          : (c-vector)  meta system observation vector
    %    OUTPUT
    %         inov            : (c-vector) innovation sequence
    [dim,nov] = size(observ);
    ffun_idx = InferenceDS.paramFFunOutIdxVec;
    dimF0 = length(ffun_idx);
    innov=zeros(InferenceDS.obsdim*nov);
    innov(1:dimF0,:) = obs(1:dimF0,:) - observ(1:dimF0,:);
    innov(dimF0+1:obsdim,:) = InferenceDS.model.innovation( InferenceDS.model, obs(dimF0+1:obsdim,:), ...
                                    observ(dimF0+1:obsdim,:));
%-------------------------------------------------------------------------------------
function llh = likelihood_parameter_bothp(InferenceDS, obs, state, U2, oNoiseDS)
    %  LIKELIHOOD_PARAMETER_BOTHP  Calculates the likelood of a real-world observation obs given
    %                           a realization of the predicted observation for a given state,
    %                           i.e. p(y|x) = p(obs|state)
    %
    %    llh = likelihood_parameter_bothp(InferenceDS, obs, observ)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         obs             : (c-vector)  real-world observation vector
    %         state           : (c-vector)  meta system state vector
    %         U2              : (c-vector) meta system exogenous input 2
    %         oNoiseDS        : (NoiseDS)   observation noise data structure
    %    OUTPUT
    %         llh             : scalar  likelihood
    [dim,nov] = size(state);
    llh = zeros(1,nov);
    dimX  = InferenceDS.model.statedim;
%    dimO  = InferenceDS.model.obsdim;
    dimU1 = InferenceDS.model.U1dim;
%    dimU2 = InferenceDS.model.U2dim;
    ext_state_1     = U2(1:dimX,:);
%    ext_U1          = U2(dimX+1:dimX+dimU1,:);
    ext_state_2     = U2(dimX+dimU1+1:dimX+dimU1+dimX,:);
    ext_U2          = U2(dimX+dimU1+dimX+1:end,:);
    ffun_idx = InferenceDS.paramFFunOutIdxVec;
    hfun_idx = InferenceDS.paramHFunOutIdxVec;
    dimF0 = length(ffun_idx);
    dimH0 = length(hfun_idx);
    ext_nextstate = obs(1:dimF0,:);
    ext_obs = obs(dimF0+1:dimF0+dimH0,:);
    % loop over all input vectors
    for k=1:nov,
        % set model parameter vector
        InferenceDS.model = InferenceDS.model.setparams( InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
        % FFUN part of likelihood
        llh_f = InferenceDS.model.prior( InferenceDS.model, ext_nextstate(:,k), ext_state_1(:,k), oNoiseDS.noiseSources{1});
        % HFUN part of likelihood
        llh_h = InferenceDS.model.likelihood( InferenceDS.model, ext_obs(:,k), ext_state_2(:,k), ext_U2(:,k), oNoiseDS.noiseSources{2});
        llh(k) = llh_f * llh_h;       % we assume independence
    end
%-------------------------------------------------------------------------------------
function observ = hfun_parameter_f(InferenceDS, state, N, U2)
    %  HFUN_PARAMETER_F   State observation function of meta system for parameter estimation using only ffun
    %                     from the underlying GSSM.
    %
    %    observ = hfun_parameter_f(InferenceDS, state, N, U2)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) meta system state vector
    %         N               : (c-vector) meta system observation noise vector
    %         U2              : (c-vector) meta system exogenous input 2
    %    OUTPUT
    %         observ          : (c-vector) meta system observation vector
    %
    % Relationship between arguments and external model (GSSM) variables
    %
    %   state  -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
    %   U2     -> [external_state(k-1) external_U1(k-1)]'
    %   N      -> [external_process_noise(k-1)]'
    %   observ -> [external_state(k)]'
    [dim,nov] = size(state);
    observ = zeros(InferenceDS.obsdim,nov);
    dimX  = InferenceDS.model.statedim;
    dimV  = InferenceDS.model.Vdim;
    dimU1 = InferenceDS.model.U1dim;
    ext_state_1     = U2(1:dimX,:);
    ext_proc_noise  = N(1:dimV,:);
    ext_U1          = U2(dimX+1:dimX+dimU1,:);
    ffun_idx = InferenceDS.paramFFunOutIdxVec;
%    dimF0 = length(ffun_idx);
    % loop over all input vectors
    for k=1:nov,
        % set model parameter vector
        InferenceDS.model = InferenceDS.model.setparams( InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
        FFunOut  = InferenceDS.model.ffun( InferenceDS.model, ext_state_1(:,k), ext_proc_noise(:,k), ext_U1(:,k));
        observ(:,k) = FFunOut(ffun_idx);
    end
%-------------------------------------------------------------------------------------
function observ = hfun_parameter_h(InferenceDS, state, N, U2)
    %  HFUN_PARAMETER_H   State observation function of meta system for parameter estimation using only hfun
    %                     from the underlying GSSM.
    %
    %    observ = hfun_parameter_h(InferenceDS, state, N, U2)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) system state vector
    %         N               : (c-vector) observation noise vector
    %         U2              : (c-vector) exogenous input 2
    %    OUTPUT
    %         observ          : (c-vector) observation vector
    %
    % Relationship between input arguments and external model (GSSM) variables
    %
    %   state  -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
    %   U2     -> [external_state(k) external_U2(k)]'
    %   N      -> [external_observation_noise(k)]'
    %   observ -> [external_observation(k)]'
    [dim,nov] = size(state);
    observ = zeros(InferenceDS.obsdim,nov);
    dimX  = InferenceDS.model.statedim;
%    dimO  = InferenceDS.model.obsdim;
    dimN  = InferenceDS.model.Ndim;
    dimU2 = InferenceDS.model.U2dim;
    ext_state_2     = U2(1:dimX,:);
    ext_U2          = U2(dimX+1:dimX+dimU2,:);
    ext_obs_noise   = N(1:dimN,:);
    hfun_idx = InferenceDS.paramHFunOutIdxVec;
%    dimH0 = length(hfun_idx);
    % loop over all input vectors
    for k=1:nov,
       % set model parameter vector
       InferenceDS.model = InferenceDS.model.setparams( InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
       HFunOut = InferenceDS.model.hfun( InferenceDS.model, ext_state_2(:,k), ext_obs_noise(:,k), ext_U2(:,k));
       observ(:,k) = HFunOut(hfun_idx);
    end
%-------------------------------------------------------------------------------------
function observ = hfun_parameter_both(InferenceDS, state, N, U2)
    %  HFUN_PARAMETER_BOTH   State observation function of meta system for parameter estimation using the full system
    %                        dynamics of the underlying GSSM as observation, i.e. observ=hfun(ffun(x))
    %
    %
    %    observ = hfun_parameter_both(InferenceDS, state, N, U2)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         state           : (c-vector) system state vector
    %         N               : (c-vector) observation noise vector
    %         U2              : (c-vector) exogenous input 2
    %    OUTPUT
    %         observ          : (c-vector) observation vector
    %
    % Relationship between input arguments and external model (GSSM) variables
    %
    %   state  -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
    %   U2     -> [external_state(k-1) external_U1(k-1) external_U2(k)]'
    %   N      -> [external_observation_noise(k)]'
    %   observ -> [external_observation(k)]'
    [dim,nov] = size(state);
    observ = zeros(InferenceDS.obsdim,nov);
    dimX  = InferenceDS.model.statedim;
    dimV  = InferenceDS.model.Vdim;
    dimN  = InferenceDS.model.Ndim;
    dimU1 = InferenceDS.model.U1dim;
    dimU2 = InferenceDS.model.U2dim;
    ext_state_1     = U2(1:dimX,:);
    ext_U1          = U2(dimX+1:dimX+dimU1,:);
    ext_U2          = U2(dimX+dimU1+1:dimX+dimU1+dimU2,:);
    ext_obs_noise   = N(dimV+1:dimV+dimN,:);
    ext_proc_noise = N(1:dimV,:);
    hfun_idx = InferenceDS.paramHFunOutIdxVec;
%    dimH0 = length(hfun_idx);
    % loop over all input vectors
    for k=1:nov,
       % set model parameter vector
       InferenceDS.model = InferenceDS.model.setparams( InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
       % calculate X(k)=ffun(X(k-1))
       ext_state_2 = InferenceDS.model.ffun( InferenceDS.model, ext_state_1(:,k), ext_proc_noise(:,k), ext_U1(:,k));
       HFunOut = InferenceDS.model.hfun( InferenceDS.model, ext_state_2, ext_obs_noise(:,k), ext_U2(:,k));
       observ(:,k) = HFunOut(hfun_idx);
    end
%-------------------------------------------------------------------------------------
function llh = likelihood_parameter_f(InferenceDS, obs, state, U2, oNoiseDS)
    %  LIKELIHOOD_PARAMETER_F  Calculates the likelood of a real-world observation obs given
    %                           a realization of the predicted observation for a given state,
    %                           i.e. p(y|x) = p(obs|state)
    %
    %    llh = likelihood_parameter_f(InferenceDS, obs, observ)
    %
    %    INPUT
    %         InferenceDS     : (InferenceDS) Inference data structure
    %         obs             : (c-vector)  real-world observation vector
    %         state           : (c-vector)  meta system state vector
    %         U2              : (c-vector) meta system exogenous input 2
    %         oNoiseDS        : (NoiseDS)   observation noise data structure
    %    OUTPUT
    %         llh             : scalar  likelihood
    [dim,nov] = size(state);
    llh = zeros(1,nov);
    dimX  = InferenceDS.model.statedim;
    dimO  = InferenceDS.model.obsdim;
    dimU1 = InferenceDS.model.U1dim;
    ext_state_1     = U2(1:dimX,:);
    ext_U1          = U2(dimX+1:dimX+dimU1,:);
    ffun_idx = InferenceDS.paramFFunOutIdxVec;
    dimF0 = length(ffun_idx);
    ext_nextstate = obs(1:dimF0,:);
    % loop over all input vectors
    for k=1:nov,
1000         % set model parameter vector
1001         InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
1002
1003         % FFUN part of likelihood
1004         llh(k) = InferenceDS.model.prior(InferenceDS.model, ext_nextstate(:,k), ext_state_1(:,k), ext_U1, oNoiseDS);
1005
1006     end
1007
1008
1009 %-------------------------------------------------------------------------------------
1010 function llh = likelihood_parameter_h(InferenceDS, obs, state, U2, oNoiseDS)
1011
1012     %  LIKELIHOOD_PARAMETER_H  Calculates the likelood of a real-world observation obs given
1013     %                           a realization of the predicted observation for a given state,
1014     %                           i.e. p(y|x) = p(obs|state)
1015     %
1016     %    llh = likelihood_parameter_h(InferenceDS, obs, observ)
1017     %
1018     %    INPUT
1019     %         InferenceDS     : (InferenceDS) Inference data structure
1020     %         obs             : (c-vector)  real-world observation vector
1021     %         state           : (c-vector)  meta system state vector
1022     %         U2              : (c-vector) meta system exogenous input 2
1023     %         oNoiseDS        : (NoiseDS)   observation noise data structure
1024     %    OUTPUT
1025     %         llh             : scalar  likelihood
1026
1027     [dim,nov] = size(state);
1028
1029     llh = zeros(1,nov);
1030
1031     dimX  = InferenceDS.model.statedim;
1032 %    dimO  = InferenceDS.model.obsdim;
1033 %    dimU2 = InferenceDS.model.U2dim;
1034
1035     ext_state_2     = U2(1:dimX,:);
1036     ext_U2          = U2(dimX+1:end,:);
1037
1038 %    hfun_idx = InferenceDS.paramHFunOutIdxVec;
1039
1040 %    dimH0 = length(hfun_idx);
1041
1042     % loop over all input vectors
1043     for k=1:nov,
1044
1045         % set model parameter vector
1046         InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
1047
1048         llh(k) = InferenceDS.model.likelihood(InferenceDS.model, obs(:,k), ext_state_2(:,k), ext_U2(:,k), oNoiseDS);
1049
1050     end
1051
1052
1053 %-------------------------------------------------------------------------------------
1054 function llh = likelihood_parameter_both(InferenceDS, obs, state, U2, oNoiseDS)
1055
1056     %  LIKELIHOOD_PARAMETER_BOTH  Calculates the likelood of a real-world observation obs given
1057     %                             a realization of the predicted observation for a given state,
1058     %                             i.e. p(y|x) = p(obs|state)
1059     %
1060     %    llh = likelihood_parameter_both(InferenceDS, obs, observ)
1061     %
1062     %    INPUT
1063     %         InferenceDS     : (InferenceDS) Inference data structure
1064     %         obs             : (c-vector)  real-world observation vector
1065     %         state           : (c-vector)  meta system state vector
1066     %         U2              : (c-vector) meta system exogenous input 2
1067     %         oNoiseDS        : (NoiseDS)   observation noise data structure
1068     %    OUTPUT
1069     %         llh             : scalar  likelihood
1070
1071     [dim,nov] = size(state);
1072
1073     llh = zeros(1,nov);
1074
1075     dimX  = InferenceDS.model.statedim;
1076 %    dimO  = InferenceDS.model.obsdim;
1077     dimU1 = InferenceDS.model.U1dim;
1078 %    dimU2 = InferenceDS.model.U2dim;
1079
1080     ext_state_1     = U2(1:dimX,:);
1081     ext_U1          = U2(dimX+1:dimX+dimU1,:);
1082     ext_U2          = U2(dimX+dimU1+1:end,:);
1083
1084 %    hfun_idx = InferenceDS.paramHFunOutIdxVec;
1085
1086 %    dimH0 = length(hfun_idx);
1087
1088         % loop over all input vectors
1089     for k=1:nov,
1090
1091         % set model parameter vector
1092         InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(:,k), InferenceDS.paramParamIdxVec);
1093
1094         ext_state_2 = InferenceDS.model.ffun(InferenceDS.model, ext_state_1(:,k), [], ext_U1(:,k));
1095
1096         llh(k) = InferenceDS.model.likelihood(InferenceDS.model, obs(:,k), ext_state_2, ext_U2(:,k), oNoiseDS);
1097
1098     end
1099
1100 %--------------------------------------------------------------------------------------
1101 function varargout = linearize_parameter_both(InferenceDS, state, V, N, U1, U2, varargin)
1102
1103     %  LINEARIZE_PARAMETER_BOTH  Linearization function of meta system for parameter estimation using both ffun
1104     %                            and hfun from the underlying GSSM in a
1105     %                            cascading (i.e. y=hfun(ffun(state,U1,V),U2,N))
1106     %
1107     %    varargout = linearize_parameter_both(InferenceDS, state, V, N, U1, U2, varargin)
1108     %
1109     %    INPUT
1110     %         InferenceDS     : (InferenceDS) Inference data structure
1111     %         state           : (c-vector) meta system state vector
1112     %         V               : (c-vector) meta system process noise vector
1113     %         N               : (c-vector) meta system observation noise vector
1114     %         U1              : (c-vector) meta system exogenous input 1
1115     %         U2              : (c-vector) meta system exogenous input 2
1116     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1117     %    OUTPUT
1118     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1119     %
1120     % Relationship between input arguments and external model (GSSM) variables
1121     %
1122     %   state -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
1123     %   U1    -> this is usually an empty matrix
1124     %   U2     -> [external_state(k-1) external_U1(k-1) external_U2(k)]'
1125     %   V     -> synthetic process noise (speeds up convergence)
1126     %   N     -> [external_process_noise(k-1) external_observation_noise(k)]'
1127
1128
1129     % Setup temporary model to use for linearization purposes
1130     model = InferenceDS.model;                                                      % copy existing model
1131     if ~isempty(state),
1132         model = model.setparams(model, state, InferenceDS.paramParamIdxVec);   % set parameters acording to state variable
1133     end
1134
1135     dimX  = model.statedim;
1136 %    dimO  = model.obsdim;
1137     dimV  = model.Vdim;
1138     dimN  = model.Ndim;
1139     dimU1 = model.U1dim;
1140 %    dimU2 = model.U2dim;
1141
1142     ext_state_1     = U2(1:dimX);
1143     ext_proc_noise  = N(1:dimV);
1144     ext_U1          = U2(dimX+1:dimX+dimU1);
1145     ext_obs_noise   = N(dimV+1:dimV+dimN);
1146     ext_U2          = U2(dimX+dimU1+1:end);
1147
1148 %    ffun_idx = InferenceDS.paramFFunOutIdxVec;
1149     hfun_idx = InferenceDS.paramHFunOutIdxVec;
1150
1151 %    dimF0 = length(ffun_idx);
1152     dimH0 = length(hfun_idx);
1153
1154     for k=1:length(varargin)
1155
1156         switch varargin{k}
1157
1158         %--- A = dffun/dstate
1159         case 'A'
1160             varargout{k} = InferenceDS.A;
1161
1162         %--- B = dffun/dU1
1163         case 'B'
1164             varargout{k} = InferenceDS.B;
1165
1166         %--- G = dffun/dv
1167         case 'G'
1168             varargout{k} = InferenceDS.G;
1169
1170         %--- C = dhfun/dstate
1171         case 'C'
1172             C = zeros(InferenceDS.obsdim, InferenceDS.statedim);
1173             ext_state_2 = model.ffun(model, ext_state_1, ext_proc_noise, ext_U1);
1174             extC = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'C');
1175             extJFW = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'JFW', InferenceDS.paramParamIdxVec);
1176             extJHW = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'JHW', InferenceDS.paramParamIdxVec);
1177             Ctemp = extC*extJFW + extJHW;
1178             C(1:dimH0,:) = Ctemp(hfun_idx,:);
1179             varargout{k} = C;
1180
1181         %--- D = dhfun/dU2
1182         case 'D'
1183             D = zeros(InferenceDS.obsdim, InferenceDS.U2dim);
1184             ext_state_2 = model.ffun(model, ext_state_1, ext_proc_noise, ext_U1);
1185             extA = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'A');
1186             extB = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'B');
1187             extC = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'C');
1188             extD = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'D');
1189             tempCA = extC*extA;
1190             tempCB = extC*extB;
1191             D(1:dimH0,1:dimX) = tempCA(hfun_idx,:);
1192             D(1:dimH0,dimX+1:dimX+dimU1) = tempCB(hfun_idx,:);
1193             D(1:dimH0,dimX+dimU1+1:end) = extD(hfun_idx,:);
1194             varargout{k} = D;
1195
1196         %--- H = dhfun/dn
1197         case 'H'
1198             H = zeros(InferenceDS.obsdim, InferenceDS.Ndim);
1199             ext_state_2 = model.ffun(model, ext_state_1, ext_proc_noise, ext_U1);
1200             extC = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'C');
1201             extG = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'G');
1202             extH = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'H');
1203             tempCG = extC*extG;
1204             H(1:dimH0,1:dimV) = tempCG(hfun_idx,:);
1205             H(1:dimH0,dimV+1:end) = extH(hfun_idx,:);
1206             varargout{k} = H;
1207
1208         %----
1209         otherwise
1210             error('[ InferenceDS.linearize ] Unknown linearization term.');
1211
1212         end
1213
1214     end
1215
1216
1217 %--------------------------------------------------------------------------------------
1218 function varargout = linearize_parameter_bothp(InferenceDS, state, V, N, U1, U2, varargin)
1219
1220     %  LINEARIZE_PARAMETER_BOTHP  Linearization function of meta system for parameter estimation using both ffun
1221     %                          and hfun from the underlying GSSM.
1222     %
1223     %    varargout = linearize_parameter_bothp(InferenceDS, state, V, N, U1, U2, varargin)
1224     %
1225     %    INPUT
1226     %         InferenceDS     : (InferenceDS) Inference data structure
1227     %         state           : (c-vector) meta system state vector
1228     %         V               : (c-vector) meta system process noise vector
1229     %         N               : (c-vector) meta system observation noise vector
1230     %         U1              : (c-vector) meta system exogenous input 1
1231     %         U2              : (c-vector) meta system exogenous input 2
1232     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1233     %    OUTPUT
1234     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1235     %
1236     % Relationship between input arguments and external model (GSSM) variables
1237     %
1238     %   state -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
1239     %   U1    -> this is usually an empty matrix
1240     %   U2    -> [external_state(k-1) external_U1(k-1) external_state(k) external_U2(k)]'
1241     %   V     -> synthetic process noise (speeds up convergence)
1242     %   N     -> [external_process_noise(k-1) external_observation_noise(k)]'
1243
1244
1245     % Setup temporary model to use for linearization purposes
1246     model = InferenceDS.model;                                                      % copy existing model
1247     if ~isempty(state),
1248         model = model.setparams(model, state, InferenceDS.paramParamIdxVec);   % set parameters according to state variable
1249     end
1250
1251     dimX  = model.statedim;
1252 %    dimO  = model.obsdim;
1253     dimV  = model.Vdim;
1254     dimN  = model.Ndim;
1255     dimU1 = model.U1dim;
1256 %    dimU2 = model.U2dim;
1257
1258     ext_state_1     = U2(1:dimX);
1259     ext_proc_noise  = N(1:dimV);
1260     ext_U1          = U2(dimX+1:dimX+dimU1);
1261     ext_state_2     = U2(dimX+dimU1+1:dimX+dimU1+dimX);
1262     ext_obs_noise   = N(dimV+1:dimV+dimN);
1263     ext_U2          = U2(dimX+dimU1+dimX+1:end);
1264
1265     ffun_idx = InferenceDS.paramFFunOutIdxVec;
1266     hfun_idx = InferenceDS.paramHFunOutIdxVec;
1267
1268     dimF0 = length(ffun_idx);
1269     dimH0 = length(hfun_idx);
1270
1271     for k=1:length(varargin)
1272
1273         switch varargin{k}
1274
1275         %--- A = dffun/dstate
1276         case 'A'
1277             varargout{k} = InferenceDS.A;
1278
1279         %--- B = dffun/dU1
1280         case 'B'
1281             varargout{k} = InferenceDS.B;
1282
1283         %--- G = dffun/dv
1284         case 'G'
1285             varargout{k} = InferenceDS.G;
1286
1287         %--- C = dhfun/dstate
1288         case 'C'
1289             C = zeros(InferenceDS.obsdim, InferenceDS.statedim);
1290             extJFW = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'JFW', InferenceDS.paramParamIdxVec);
1291             extJHW = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'JHW', InferenceDS.paramParamIdxVec);
1292             C(1:dimF0,:) = extJFW(ffun_idx,:);
1293             C(dimF0+1:dimF0+dimH0,:) = extJHW(hfun_idx,:);
1294             varargout{k} = C;
1295
1296         %--- D = dhfun/dU2
1297         case 'D'
1298             D = zeros(InferenceDS.obsdim, InferenceDS.U2dim);
1299             extA = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'A');
1300             extB = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'B');
1301             extC = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'C');
1302             extD = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'D');
1303             D(1:dimF0,1:dimX) = extA(ffun_idx,:);
1304             D(1:dimF0,dimX+1:dimX+dimU1) = extB(ffun_idx,:);
1305             D(dimF0+1:dimF0+dimH0,dimX+dimU1+1:dimX+dimU1+dimX) = extC(hfun_idx,:);
1306             D(dimF0+1:dimF0+dimH0,dimX+dimU1+dimX+1:end) = extD(hfun_idx,:);
1307             varargout{k} = D;
1308
1309         %--- H = dhfun/dn
1310         case 'H'
1311             H = zeros(InferenceDS.obsdim, InferenceDS.Ndim);
1312             extG = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'G');
1313             extH = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'H');
1314             H(1:dimF0,1:dimV) = extG(ffun_idx,:);
1315             H(dimF0+1:dimF0+dimH0,dimV+1:end) = extH(hfun_idx,:);
1316             varargout{k} = H;
1317
1318         %----
1319         otherwise
1320             error('[ InferenceDS.linearize ] Unknown linearization term.');
1321
1322         end
1323
1324     end
1325
1326 %-------------------------------------------------------------------------------------
1327 function varargout = linearize_parameter_f(InferenceDS, state, V, N, U1, U2, varargin)
1328
1329     %  LINEARIZE_PARAMETER_F  Linearization function of meta system for parameter estimation using only
1330     %                         ffun from the underlying GSSM.
1331     %
1332     %    varargout = linearize_parameter_f(InferenceDS, state, V, N, U1, U2, varargin)
1333     %
1334     %    INPUT
1335     %         InferenceDS     : (InferenceDS) Inference data structure
1336     %         state           : (c-vector) meta system state vector
1337     %         V               : (c-vector) meta system process noise vector
1338     %         N               : (c-vector) meta system observation noise vector
1339     %         U1              : (c-vector) meta system exogenous input 1
1340     %         U2              : (c-vector) meta system exogenous input 2
1341     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1342     %    OUTPUT
1343     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1344     %
1345     % Relationship between input arguments and external model (GSSM) variables
1346     %
1347     %   state -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
1348     %   U1    -> this is usually an empty matrix
1349     %   U2    -> [external_state(k-1) external_U1(k-1)]'
1350     %   V     -> synthetic process noise (speeds up convergence)
1351     %   N     -> [external_process_noise(k-1)]'
1352
1353
1354     % Setup temporary model to use for linearization purposes
1355     model = InferenceDS.model;                                                        % copy existing model
1356     if ~isempty(state),
1357         model = model.setparams(model, state, InferenceDS.paramParamIdxVec);   % set parameters acording to state variable
1358     end
1359
1360     dimX  = model.statedim;
1361     dimV  = model.Vdim;
1362     dimU1 = model.U1dim;
1363
1364     if isempty(U2)
1365         ext_state_1     = [];
1366         ext_U1          = [];
1367     else
1368         ext_state_1     = U2(1:dimX);
1369         ext_U1          = U2(dimX+1:dimX+dimU1);
1370     end
1371     if isempty(N),
1372         ext_proc_noise  = [];
1373     else
1374         ext_proc_noise  = N(1:dimV);
1375     end
1376
1377     ffun_idx = InferenceDS.paramFFunOutIdxVec;
1378
1379     dimF0 = length(ffun_idx);
1380
1381
1382     for k=1:length(varargin)
1383
1384         switch varargin{k}
1385
1386         %--- A = dffun/dstate
1387         case 'A'
1388             varargout{k} = InferenceDS.A;
1389
1390         %--- B = dffun/dU1
1391         case 'B'
1392             varargout{k} = InferenceDS.B;
1393
1394         %--- G = dffun/dv
1395         case 'G'
1396             varargout{k} = InferenceDS.G;
1397
1398         %--- C = dhfun/dstate
1399         case 'C'
1400             C = zeros(InferenceDS.obsdim, InferenceDS.statedim);
1401             extJFW = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'JFW', InferenceDS.paramParamIdxVec);
1402             C = extJFW(ffun_idx,:);
1403             varargout{k} = C;
1404
1405         %--- D = dhfun/dU2
1406         case 'D'
1407             D = zeros(InferenceDS.obsdim, InferenceDS.U2dim);
1408             extA = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'A');
1409             extB = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'B');
1410             D(1:dimF0,1:dimX) = extA(ffun_idx,:);
1411             D(1:dimF0,dimX+1:dimX+dimU1) = extB(ffun_idx,:);
1412             varargout{k} = D;
1413
1414         %--- H = dhfun/dn
1415         case 'H'
1416             H = zeros(InferenceDS.obsdim, InferenceDS.Ndim);
1417             extG = model.linearize(model, ext_state_1, ext_proc_noise, [], ext_U1, [], 'G');
1418             H(1:dimF0,1:dimV) = extG(ffun_idx,:);
1419             varargout{k} = H;
1420
1421         %---
1422         otherwise
1423             error('[ InferenceDS.linearize ] Unknown linearization term.');
1424
1425         end
1426
1427     end
1428
1429
1430 %-------------------------------------------------------------------------------------
1431 function varargout = linearize_parameter_h(InferenceDS, state, V, N, U1, U2, varargin)
1432
1433     %  LINEARIZE_PARAMETER_H  Linearization function of meta system for parameter estimation using
1434     %                         only hfun from the underlying GSSM.
1435     %
1436     %    varargout = linearize_parameter_h(InferenceDS, state, V, N, U1, U2, varargin)
1437     %
1438     %    INPUT
1439     %         InferenceDS     : (InferenceDS) Inference data structure
1440     %         state           : (c-vector) meta system state vector
1441     %         V               : (c-vector) meta system process noise vector
1442     %         N               : (c-vector) meta system observation noise vector
1443     %         U1              : (c-vector) meta system exogenous input 1
1444     %         U2              : (c-vector) meta system exogenous input 2
1445     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1446     %    OUTPUT
1447     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1448     %
1449     % Relationship between input arguments and external model (GSSM) variables
1450     %
1451     %   state -> external model parameters or a subset (specified by InferenceDS.paramParamIdxVec) thereof
1452     %   U1    -> this is usually an empty matrix
1453     %   U2    -> [external_state(k) external_U2(k)]'
1454     %   V     -> synthetic process noise (speeds up convergence)
1455     %   N     -> [external_observation_noise(k)]'
1456
1457
1458     % Setup temporary model to use for linearization purposes
1459     model = InferenceDS.model;                                                     % copy existing model
1460     model = model.setparams(model, state, InferenceDS.paramParamIdxVec);       % set parameters acording to state variable
1461
1462     dimX  = model.statedim;
1463 %    dimO  = model.obsdim;
1464     dimN  = model.Ndim;
1465     dimU2 = model.U2dim;
1466
1467     ext_state_2     = U2(1:dimX);
1468     ext_obs_noise   = N(1:dimN);
1469     ext_U2          = U2(dimX+1:dimX+dimU2);
1470
1471     hfun_idx = InferenceDS.paramHFunOutIdxVec;
1472
1473     dimH0 = length(hfun_idx);
1474
1475
1476     for k=1:length(varargin),
1477
1478         switch varargin{k}
1479
1480         %--- A = dffun/dstate
1481         case 'A'
1482             varargout{k} = InferenceDS.A;
1483
1484         %--- B = dffun/dU1
1485         case 'B'
1486             varargout{k} = InferenceDS.B;
1487
1488         %--- G = dffun/dv
1489         case 'G'
1490             varargout{k} = InferenceDS.G;
1491
1492
1493         %--- C = dhfun/dstate
1494         case 'C'
1495 %            C = zeros(InferenceDS.obsdim, InferenceDS.statedim);
1496             extJHW = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'JHW', InferenceDS.paramParamIdxVec);
1497             varargout{k} = extJHW(hfun_idx,:);
1498
1499
1500         %--- D = dhfun/dU2
1501         case 'D'
1502             D = zeros(InferenceDS.obsdim, InferenceDS.U2dim);
1503             extC = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'C');
1504             extD = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'D');
1505             D(1:dimH0,1:dimX) = extC(hfun_idx,:);
1506             D(1:dimH0,dimX+1:dimX+dimU2) = extD(hfun_idx,:);
1507             varargout{k} = D;
1508
1509
1510         %--- H = dhfun/dn
1511         case 'H'
1512             H = zeros(InferenceDS.obsdim, InferenceDS.Ndim);
1513             extH = model.linearize(model, ext_state_2, [], ext_obs_noise, [], ext_U2, 'H');
1514             H(1:dimH0,1:dimN) = extH(hfun_idx,:);
1515             varargout{k} = H;
1516
1517         %---
1518         otherwise
1519             error('[ InferenceDS.linearize ] Unknown linearization term.');
1520
1521         end
1522
1523     end
1524
1525
1526 %===================================================================================================
1527 %================================= JOINT ESTIMATION FUNCTIONS ======================================
1528
1529 function new_state = ffun_joint(InferenceDS, state, V, U1)
1530
1531     %  FFUN_JOINT  State transition function of meta system for joint estimation
1532     %
1533     %    new_state = ffun_joint(InferenceDS, state, V, U1)
1534     %
1535     %    INPUT
1536     %         InferenceDS     : (InferenceDS) Inference data structure
1537     %         state           : (c-vector) meta system state vector
1538     %         V               : (c-vector) meta system process noise vector
1539     %         U1              : (c-vector) meta system exogenous input 1
1540     %    OUTPUT
1541     %         new_state       : (c-vector) updated meta system state vector
1542
1543     [dim,nov] = size(state);
1544
1545     new_state = zeros(dim,nov);
1546
1547     dimX  = InferenceDS.model.statedim;
1548     dimV  = InferenceDS.model.Vdim;
1549
1550     for k=1:nov,
1551       InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(dimX+1:end,k), InferenceDS.paramParamIdxVec);    % set model parameter vector
1552       new_state(1:dimX,k) = InferenceDS.model.ffun(InferenceDS.model, state(1:dimX,k), V(1:dimV,k), U1(:,k));
1553       new_state(dimX+1:end,k) = state(dimX+1:end,k) + V(dimV+1:end,k);
1554     end
1555
1556 %-------------------------------------------------------------------------------------
1557 function tran_prior = prior_joint(InferenceDS, nextstate, state, U1, pNoiseDS)
1558
1559     %  PRIOR_JOINT  Calculates the transition prior probability P(x_k|x_(k-1))
1560     %
1561     %    tranprior = prior_joint(InferenceDS, nextstate, state, pNoiseDS)
1562     %
1563     %    INPUT
1564     %         InferenceDS     : (InferenceDS) Inference data structure
1565     %         nextstate       : (c-vector)  system state at time k
1566     %         state           : (c-vector)  system state at time k-1
1567     %         U1              : (c-vector) meta system exogenous input 1
1568     %         pNoiseDS        : (NoiseDS)   process noise data structure
1569     %    OUTPUT
1570     %         tranprior       : scalar probability P(x_k|x_(k-1))
1571
1572
1573     [dim,nov] = size(state);
1574
1575     tran_prior = zeros(1,nov);
1576
1577     dimX  = InferenceDS.model.statedim;
1578
1579     paramState = state(dimX+1:end,:);
1580     paramNextState = nextstate(dimX+1:end,:);
1581
1582     stateState = state(1:dimX,:);
1583     stateNextState = nextstate(1:dimX,:);
1584
1585     dX = paramNextState - paramState;
1586
1587     tran_prior = pNoiseDS.likelihood(pNoiseDS, dX, pNoiseDS.N);
1588
1589     for k=1:nov,
1590         InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, paramState(:,k), InferenceDS.paramParamIdxVec); % set model parameter vector
1591         tran_prior(k) = tran_prior(k) * InferenceDS.model.prior(InferenceDS.model, stateNextState(:,k), stateState(:,k), U1(:,k), pNoiseDS.noiseSources{1});
1592     end
1593
1594 %-------------------------------------------------------------------------------------
1595 function observ = hfun_joint(InferenceDS, state, N, U2)
1596
1597     %  HFUN_JOINT  State observation function of meta system for joint estimation
1598     %
1599     %    observ = hfun_joint(InferenceDS, state, N, U2)
1600     %
1601     %    INPUT
1602     %         InferenceDS     : (InferenceDS) Inference data structure
1603     %         state           : (c-vector) meta system state vector
1604     %         N               : (c-vector) meta system observation noise vector
1605     %         U2              : (c-vector) meta system exogenous input 2
1606     %    OUTPUT
1607     %         observ          : (c-vector)  meta system observation vector
1608
1609     [dim,nov] = size(state);
1610
1611     observ = zeros(InferenceDS.obsdim,nov);
1612
1613     dimX  = InferenceDS.model.statedim;
1614 %    dimV  = InferenceDS.model.Vdim;
1615
1616     for k=1:nov,
1617       InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(dimX+1:end,k), InferenceDS.paramParamIdxVec);    % set model parameter vector
1618       observ(:,k) = InferenceDS.model.hfun(InferenceDS.model, state(1:dimX,k), N(:,k), U2(:,k));
1619     end
1620
1621 %-------------------------------------------------------------------------------------
1622 function llh = likelihood_joint(InferenceDS, obs, state, U2, oNoiseDS)
1623
1624     %  LIKELIHOOD_JOINT  Calculates the likelood of a real-world observation obs given
1625     %                           a realization of the predicted observation for a given state,
1626     %                           i.e. p(y|x) = p(obs|state)
1627     %
1628     %    llh = likelihood_joint(InferenceDS, obs, observ)
1629     %
1630     %    INPUT
1631     %         InferenceDS     : (InferenceDS) Inference data structure
1632     %         obs             : (c-vector)  real-world observation vector
1633     %         state           : (c-vector)  meta system state vector
1634     %         U2              : (c-vector) meta system exogenous input 2
1635     %         oNoiseDS        : (NoiseDS)   observation noise data structure
1636     %    OUTPUT
1637     %         llh             : scalar  likelihood
1638
1639     [dim,nov] = size(state);
1640
1641     llh = zeros(1,nov);
1642
1643     dimX  = InferenceDS.model.statedim;
1644
1645     for k=1:nov,
1646       InferenceDS.model = InferenceDS.model.setparams(InferenceDS.model, state(dimX+1:end,k), InferenceDS.paramParamIdxVec); ...
1647       % set model parameter vector
1648       llh(k) = InferenceDS.model.likelihood(InferenceDS.model, obs(:,k), state(1:dimX,k), U2(:,k), oNoiseDS);
1649     end
1650
1651
1652 %-------------------------------------------------------------------------------------
1653 function varargout = linearize_joint(InferenceDS, state, V, N, U1, U2, varargin)
1654
1655     %  LINEARIZE_JOINT  Linearization function of meta system for state estimation
1656     %
1657     %    varargout = linearize_joint(InferenceDS, state, V, N, U1, U2, varargin)
1658     %
1659     %    INPUT
1660     %         InferenceDS     : (InferenceDS) Inference data structure
1661     %         state           : (c-vector) meta system state vector
1662     %         V               : (c-vector) meta system process noise vector
1663     %         N               : (c-vector) meta system observation noise vector
1664     %         U1              : (c-vector) meta system exogenous input 1
1665     %         U2              : (c-vector) meta system exogenous input 2
1666     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1667     %    OUTPUT
1668     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1669
1670     model = InferenceDS.model;                                                     % copy existing model
1671
1672     dimX  = model.statedim;
1673 %    dimO  = model.obsdim;
1674 %    dimN  = model.Ndim;
1675     dimV  = model.Vdim;
1676
1677     paramIdxVec = InferenceDS.paramParamIdxVec;
1678     dimW  = length(paramIdxVec);
1679     ext_state  = state(1:dimX);
1680     ext_params = state(dimX+1:dimX+dimW);
1681     ext_V      = V(1:dimV);
1682 %    param_V    = V(dimV+1:dimV+dimW);
1683
1684     % Setup temporary model to use for linearization purposes
1685     model = model.setparams(model, ext_params, paramIdxVec);       % set parameters acording to state variable
1686
1687
1688     nop = length(varargin);
1689
1690     for k=1:nop,
1691
1692         switch varargin{k}
1693
1694          case 'A'
1695             A = eye(InferenceDS.statedim);
1696             A(1:dimX,1:dimX) = model.linearize(model, ext_state, ext_V, N, U1, U2, 'A');
1697             A(1:dimX,dimX+1:dimX+dimW) = model.linearize(model, ext_state, ext_V, N, U1, U2, 'JFW', paramIdxVec);
1698             varargout{k} = A;
1699
1700         case 'B'
1701             B = zeros(InferenceDS.statedim,InferenceDS.U1dim);
1702             B(1:dimX,:) = model.linearize(model, ext_state, ext_V, N, U1, U2, 'B');
1703             varargout{k} = B;
1704
1705         case 'G'
1706             G = zeros(InferenceDS.statedim,InferenceDS.Vdim);
1707             G(1:dimX,1:dimV) = model.linearize(model, ext_state, ext_V, N, U1, U2, 'G');
1708             G(dimX+1:dimX+dimW,dimV+1:dimV+dimW) = eye(dimW);
1709             varargout{k} = G;
1710
1711          case 'C'
1712             C = zeros(InferenceDS.obsdim,InferenceDS.statedim);
1713             C(:,1:dimX) =  model.linearize(model, ext_state, ext_V, N, U1, U2, 'C');
1714             C(:,dimX+1:dimX+dimW) = model.linearize(model, ext_state, ext_V, N, U1, U2, 'JHW', paramIdxVec);
1715             varargout{k} = C;
1716
1717          case 'D'
1718             varargout{k} = model.linearize(model, ext_state, ext_V, N, U1, U2, 'D');
1719
1720          case 'H'
1721             varargout{k} = model.linearize(model, ext_state, ext_V, N, U1, U2, 'H');
1722
1723         end
1724
1725
1726     end
1727
1728
1729
1730 %-------------------------------------------------------------------------------------
1731 function innov = innovation_generic(InferenceDS, obs, observ)
1732
1733     %  INNOVATION_GENERIC  Calculates the innovation signal (difference) between the
1734     %   output of HFUN, i.e. OBSERV (the predicted system observation) and an actual
1735     %   'real world' observation OBS.
1736     %
1737     %   innov = innovation_generic(InferenceDS, obs, observ)
1738     %
1739     %    INPUT
1740     %         InferenceDS     : (InferenceDS) Inference data structure
1741     %         obs             : (c-vector)  real-world observation vector
1742     %         observ          : (c-vector)  meta system generated observation vector
1743     %    OUTPUT
1744     %         inov            : (c-vector) innovation sequence
1745
1746     innov = obs - observ;
1747
1748
1749 %-------------------------------------------------------------------------------------
1750 function varargout = linearize_generic(InferenceDS, state, V, N, U1, U2, varargin)
1751
1752     %  LINEARIZE_GENERIC  Generic (perturbation based) linearization function of meta system
1753     %
1754     %    varargout = linearize_generic(InferenceDS, state, V, N, U1, U2, varargin)
1755     %
1756     %    INPUT
1757     %         InferenceDS     : (InferenceDS) Inference data structure
1758     %         state           : (c-vector) meta system state vector
1759     %         V               : (c-vector) meta system process noise vector
1760     %         N               : (c-vector) meta system observation noise vector
1761     %         U1              : (c-vector) meta system exogenous input 1
1762     %         U2              : (c-vector) meta system exogenous input 2
1763     %         varargin        : (strings) linearization terms wanted, e.g. 'A','B','G',....
1764     %    OUTPUT
1765     %         varargout       : (matrices) linearization terms corresponding with varargin strings
1766
1767   nop = length(varargin);
1768
1769   epsilon = 1e-8;                    % perturbation step size
1770
1771   for k=1:nop,
1772
1773       switch varargin{k}
1774
1775       case 'A'
1776       %%%========================================================
1777       %%%             Calculate A = dffun/dstate
1778       %%%========================================================
1779       A  = zeros(InferenceDS.statedim);
1780       S = cvecrep(state, InferenceDS.statedim+1);
1781       S(:,2:end) = S(:,2:end)+diag(cvecrep(epsilon,InferenceDS.statedim));
1782       F = InferenceDS.ffun(InferenceDS, S, cvecrep(V,InferenceDS.statedim+1), cvecrep(U1,InferenceDS.statedim+1));
1783       A = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.statedim))./epsilon;
1784       varargout{k} = A;
1785
1786
1787       case 'B'
1788       %%%========================================================
1789       %%%             Calculate B = dffun/dU1
1790       %%%========================================================
1791       %%%========================================================
1792       B = zeros(InferenceDS.statedim,InferenceDS.U1dim);
1793       U = cvecrep(U1, InferenceDS.U1dim+1);
1794       U(:,2:end) = U(:,2:end)+diag(cvecrep(epsilon,InferenceDS.U1dim));
1795       F = InferenceDS.ffun(InferenceDS, cvecrep(state,InferenceDS.U1dim+1, cvecrep(V,InferenceDS.U1dim+1), U));
1796       B = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.U1dim))./epsilon;
1797       varargout{k} = B;
1798
1799
1800       case 'G'
1801       %%%========================================================
1802       %%%             Calculate G = dffun/dv
1803       %%%========================================================
1804       G = zeros(InferenceDS.statedim,InferenceDS.Vdim);
1805       VV = cvecrep(V, InferenceDS.Vdim+1);
1806       VV(:,2:end) = VV(:,2:end)+diag(cvecrep(epsilon,InferenceDS.Vdim));
1807       F = InferenceDS.ffun(InferenceDS, cvecrep(state,InferenceDS.Vdim+1), VV, cvecrep(U1,InferenceDS.Vdim+1));
1808       G = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.Vdim))./epsilon;
1809       varargout{k} = G;
1810
1811
1812       case 'C'
1813       %%%========================================================
1814       %%%             Calculate C = dhfun/dx
1815       %%%========================================================
1816       C = zeros(InferenceDS.obsdim,InferenceDS.statedim);
1817       S = cvecrep(state, InferenceDS.statedim+1);
1818       S(:,2:end) = S(:,2:end)+diag(cvecrep(epsilon,InferenceDS.statedim));
1819       F = InferenceDS.hfun(InferenceDS, S, cvecrep(N,InferenceDS.statedim+1), cvecrep(U2,InferenceDS.statedim+1));
1820       C = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.statedim))./epsilon;
1821       varargout{k} = C;
1822
1823
1824       case 'D'
1825       %%%========================================================
1826       %%%             Calculate D = dhfun/dU2
1827       %%%========================================================
1828       %%%========================================================
1829       D = zeros(InferenceDS.obsdim,InferenceDS.U2dim);
1830       U = cvecrep(U2, InferenceDS.U2dim+1);
1831       U(:,2:end) = U(:,2:end)+diag(cvecrep(epsilon,InferenceDS.U2dim));
1832       F = InferenceDS.hfun(InferenceDS, cvecrep(state,InferenceDS.U2dim+1, cvecrep(N,InferenceDS.U2dim+1), U));
1833       D = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.U2dim))./epsilon;
1834       varargout{k} = B;
1835
1836       case 'H'
1837       %%%========================================================
1838       %%%             Calculate H = dhfun/dn
1839       %%%========================================================
1840       H = zeros(InferenceDS.obsdim,InferenceDS.Ndim);
1841       NN = cvecrep(N, InferenceDS.Ndim+1);
1842       NN(:,2:end) = NN(:,2:end)+diag(cvecrep(epsilon,InferenceDS.Ndim));
1843       F = InferenceDS.hfun(InferenceDS, cvecrep(state,InferenceDS.Ndim+1), NN, cvecrep(U2,InferenceDS.Ndim+1));
1844       H = (F(:,2:end)-cvecrep(F(:,1),InferenceDS.Ndim))./epsilon;
1845       varargout{k} = H;
1846
1847       otherwise
1848         error('[ linearize_generic ] Invalid linearization term requested!');
1849
1850       end
1851
1852
1853   end
1854