Description of stringmatch
Home > ReBEL-0.2.7 > core > stringmatch.m
stringmatch
PURPOSE
STRINGMATCH Returns match > 0 if string1 and string2 match (string2 can be a cell array of
SYNOPSIS
function match = stringmatch(string1,string2)
DESCRIPTION
 STRINGMATCH  Returns match > 0 if string1 and string2 match (string2 can be a cell array of
              strings). match = 0 is returned if not match is found.
   match = stringmatch(string1,string2)
   Copyright (c) Oregon Health & Science University (2006)
   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
   academic use only (see included license file) and can be obtained from
   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
   software should contact rebel@csee.ogi.edu for commercial licensing information.
   See LICENSE (which should be part of the main toolkit distribution) for more
   detail.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
consistent CONSISTENT Check ReBEL data structures for consistentency.
convgausns CONVGAUSNS Convert Gaussian noise source from one cov_type to another
geninfds GENINFDS Generate inference data structure from a generalized state space model and user defined inference parameters.
gennoiseds GENNOISEDS Generates a NoiseDS data structure describing a noise source.
gensysnoiseds GENSYSNOISEDS Generate process and observation noise data structures for a given InferenceDS data structure
dempe1 DEMPE1 Demonstrate parameter estimation on a simple 2nd order LTI system.
SOURCE CODE
function match = stringmatch(string1,string2)
% STRINGMATCH  Returns match > 0 if string1 and string2 match (string2 can be a cell array of
%              strings). match = 0 is returned if not match is found.
%
%   match = stringmatch(string1,string2)
%
%   Copyright (c) Oregon Health & Science University (2006)
%
%   This file is part of the ReBEL Toolkit. The ReBEL Toolkit is available free for
%   academic use only (see included license file) and can be obtained from
%   http://choosh.csee.ogi.edu/rebel/.  Businesses wishing to obtain a copy of the
%   software should contact rebel@csee.ogi.edu for commercial licensing information.
%
%   See LICENSE (which should be part of the main toolkit distribution) for more
%   detail.
%=============================================================================================
  match = sum(strcmp(string1,string2));