Description of consist
Home > ReBEL-0.2.7 > netlab > consist.m
consist
PURPOSE
CONSIST Check that arguments are consistent.
SYNOPSIS
function errstring = consist(model, type, inputs, outputs)
DESCRIPTION
CONSIST Check that arguments are consistent.
   Description
   ERRSTRING = CONSIST(NET, TYPE, INPUTS) takes a network data structure
   NET together with a string TYPE containing the correct network type,
   a matrix INPUTS of input vectors and checks that the data structure
   is consistent with the other arguments.  An empty string is returned
   if there is no error, otherwise the string contains the relevant
   error message.  If the TYPE string is empty, then any type of network
   is allowed.
   ERRSTRING = CONSIST(NET, TYPE) takes a network data structure NET
   together with a string TYPE containing the correct  network type, and
   checks that the two types match.
   ERRSTRING = CONSIST(NET, TYPE, INPUTS, OUTPUTS) also checks that the
   network has the correct number of outputs, and that the number of
   patterns in the INPUTS and OUTPUTS is the same.  The fields in NET
   that are used are
     type
     nin
     nout
   See also
   MLPFWD
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
evidence EVIDENCE Re-estimate hyperparameters using evidence approximation.
glmderiv GLMDERIV Evaluate derivatives of GLM outputs with respect to weights.
glmerr GLMERR Evaluate error function for generalized linear model.
glmfwd GLMFWD Forward propagation through generalized linear model.
glmgrad GLMGRAD Evaluate gradient of error function for generalized linear model.
glmhess GLMHESS Evaluate the Hessian matrix for a generalised linear model.
glminit GLMINIT Initialise the weights in a generalized linear model.
glmpak GLMPAK Combines weights and biases into one weights vector.
glmtrain GLMTRAIN Specialised training of generalized linear model
glmunpak GLMUNPAK Separates weights vector into weight and bias matrices.
gmmactiv GMMACTIV Computes the activations of a Gaussian mixture model.
gmmem GMMEM EM algorithm for Gaussian mixture model.
gmminit GMMINIT Initialises Gaussian mixture model from data
gmmpak GMMPAK Combines all the parameters in a Gaussian mixture model into one vector.
gmmpost GMMPOST Computes the class posterior probabilities of a Gaussian mixture model.
gmmprob GMMPROB Computes the data probability for a Gaussian mixture model.
gmmsamp GMMSAMP Sample from a Gaussian mixture distribution.
gmmunpak GMMUNPAK Separates a vector of Gaussian mixture model parameters into its components.
gpcovar GPCOVAR Calculate the covariance for a Gaussian Process.
gpcovarf GPCOVARF Calculate the covariance function for a Gaussian Process.
gpcovarp GPCOVARP Calculate the prior covariance for a Gaussian Process.
gperr GPERR Evaluate error function for Gaussian Process.
gpfwd GPFWD Forward propagation through Gaussian Process.
gpgrad GPGRAD Evaluate error gradient for Gaussian Process.
gpinit GPINIT Initialise Gaussian Process model.
gppak GPPAK Combines GP hyperparameters into one vector.
gpunpak GPUNPAK Separates hyperparameter vector into components.
gtmem GTMEM EM algorithm for Generative Topographic Mapping.
gtminit GTMINIT Initialise the weights and latent sample in a GTM.
gtmlmean GTMLMEAN Mean responsibility for data in a GTM.
gtmlmode GTMLMODE Mode responsibility for data in a GTM.
gtmmag GTMMAG Magnification factors for a GTM
gtmpost GTMPOST Latent space responsibility for data in a GTM.
gtmprob GTMPROB Probability for data under a GTM.
knn KNN Creates a K-nearest-neighbour classifier.
knnfwd KNNFWD Forward propagation through a K-nearest-neighbour classifier.
mdn2gmm MDN2GMM Converts an MDN mixture data structure to array of GMMs.
mdndist2 MDNDIST2 Calculates squared distance between centres of Gaussian kernels and data
mdnerr MDNERR Evaluate error function for Mixture Density Network.
mdnfwd MDNFWD Forward propagation through Mixture Density Network.
mdngrad MDNGRAD Evaluate gradient of error function for Mixture Density Network.
mdnpak MDNPAK Combines weights and biases into one weights vector.
mdnprob MDNPROB Computes the data probability likelihood for an MDN mixture structure.
mdnunpak MDNUNPAK Separates weights vector into weight and bias matrices.
mlpderiv MLPDERIV Evaluate derivatives of network outputs with respect to weights.
mlperr MLPERR Evaluate error function for 2-layer network.
mlpfwd MLPFWD Forward propagation through 2-layer network.
mlpgrad MLPGRAD Evaluate gradient of error function for 2-layer network.
mlphdotv MLPHDOTV Evaluate the product of the data Hessian with a vector.
mlphess MLPHESS Evaluate the Hessian matrix for a multi-layer perceptron network.
mlppak MLPPAK Combines weights and biases into one weights vector.
mlpunpak MLPUNPAK Separates weights vector into weight and bias matrices.
rbfderiv RBFDERIV Evaluate derivatives of RBF network outputs with respect to weights.
rbferr RBFERR Evaluate error function for RBF network.
rbffwd RBFFWD Forward propagation through RBF network with linear outputs.
rbfgrad RBFGRAD Evaluate gradient of error function for RBF network.
rbfhess RBFHESS Evaluate the Hessian matrix for RBF network.
rbfjacob RBFJACOB Evaluate derivatives of RBF network outputs with respect to inputs.
rbfpak RBFPAK Combines all the parameters in an RBF network into one weights vector.
rbfsetbf RBFSETBF Set basis functions of RBF from data.
rbftrain RBFTRAIN Two stage training of RBF network.
rbfunpak RBFUNPAK Separates a vector of RBF weights into its components.
somfwd SOMFWD Forward propagation through a Self-Organising Map.
sompak SOMPAK Combines node weights into one weights matrix.
somtrain SOMTRAIN Kohonen training algorithm for SOM.
somunpak SOMUNPAK Replaces node weights in SOM.
SOURCE CODE
function errstring = consist(model, type, inputs, outputs)
%CONSIST Check that arguments are consistent.
%
%   Description
%
%   ERRSTRING = CONSIST(NET, TYPE, INPUTS) takes a network data structure
%   NET together with a string TYPE containing the correct network type,
%   a matrix INPUTS of input vectors and checks that the data structure
%   is consistent with the other arguments.  An empty string is returned
%   if there is no error, otherwise the string contains the relevant
%   error message.  If the TYPE string is empty, then any type of network
%   is allowed.
%
%   ERRSTRING = CONSIST(NET, TYPE) takes a network data structure NET
%   together with a string TYPE containing the correct  network type, and
%   checks that the two types match.
%
%   ERRSTRING = CONSIST(NET, TYPE, INPUTS, OUTPUTS) also checks that the
%   network has the correct number of outputs, and that the number of
%   patterns in the INPUTS and OUTPUTS is the same.  The fields in NET
%   that are used are
%     type
%     nin
%     nout
%
%   See also
%   MLPFWD
%
%   Copyright (c) Ian T Nabney (1996-2001)
% Assume that all is OK as default
errstring = '';
% If type string is not empty
if ~isempty(type)
  % First check that model has type field
  if ~isfield(model, 'type')
    errstring = 'Data structure does not contain type field';
    return
  end
  % Check that model has the correct type
  s = model.type;
  if ~strcmp(s, type)
    errstring = ['Model type ''', s, ''' does not match expected type ''',...
    type, ''''];
    return
  end
end
% If inputs are present, check that they have correct dimension
if nargin > 2
  if ~isfield(model, 'nin')
    errstring = 'Data structure does not contain nin field';
    return
  end
  data_nin = size(inputs, 2);
  if model.nin ~= data_nin
    errstring = ['Dimension of inputs ', num2str(data_nin), ...
    ' does not match number of model inputs ', num2str(model.nin)];
    return
  end
end
% If outputs are present, check that they have correct dimension
if nargin > 3
  if ~isfield(model, 'nout')
    errstring = 'Data structure does not conatin nout field';
    return
  end
  data_nout = size(outputs, 2);
  if model.nout ~= data_nout
    errstring = ['Dimension of outputs ', num2str(data_nout), ...
    ' does not match number of model outputs ', num2str(model.nout)];
    return
  end
% Also check that number of data points in inputs and outputs is the same
  num_in = size(inputs, 1);
  num_out = size(outputs, 1);
  if num_in ~= num_out
    errstring = ['Number of input patterns ', num2str(num_in), ...
    ' does not match number of output patterns ', num2str(num_out)];
    return
  end
end