Description of dist2
Home > ReBEL-0.2.7 > netlab > dist2.m
dist2
PURPOSE
DIST2 Calculates squared distance between two sets of points.
SYNOPSIS
function n2 = dist2(x, c)
DESCRIPTION
DIST2    Calculates squared distance between two sets of points.
    Description
    D = DIST2(X, C) takes two matrices of vectors and calculates the
    squared Euclidean distance between them.  Both matrices must be of
    the same column dimension.  If X has M rows and N columns, and C has
    L rows and N columns, then the result has M rows and L columns.  The
    I, Jth entry is the  squared distance from the Ith row of X to the
    Jth row of C.
    See also
    GMMACTIV, KMEANS, RBFFWD
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gmmactiv GMMACTIV Computes the activations of a Gaussian mixture model.
gmmem GMMEM EM algorithm for Gaussian mixture model.
gmminit GMMINIT Initialises Gaussian mixture model from data
gtmem GTMEM EM algorithm for Generative Topographic Mapping.
gtminit GTMINIT Initialise the weights and latent sample in a GTM.
kmeans KMEANS Trains a k means cluster model.
knnfwd KNNFWD Forward propagation through a K-nearest-neighbour classifier.
mdngrad MDNGRAD Evaluate gradient of error function for Mixture Density Network.
mdnprob MDNPROB Computes the data probability likelihood for an MDN mixture structure.
rbferr RBFERR Evaluate error function for RBF network.
rbffwd RBFFWD Forward propagation through RBF network with linear outputs.
rbfgrad RBFGRAD Evaluate gradient of error function for RBF network.
rbfsetfw RBFSETFW Set basis function widths of RBF.
rbftrain RBFTRAIN Two stage training of RBF network.
somfwd SOMFWD Forward propagation through a Self-Organising Map.
somtrain SOMTRAIN Kohonen training algorithm for SOM.
SOURCE CODE
function n2 = dist2(x, c)
%DIST2    Calculates squared distance between two sets of points.
%
%    Description
%    D = DIST2(X, C) takes two matrices of vectors and calculates the
%    squared Euclidean distance between them.  Both matrices must be of
%    the same column dimension.  If X has M rows and N columns, and C has
%    L rows and N columns, then the result has M rows and L columns.  The
%    I, Jth entry is the  squared distance from the Ith row of X to the
%    Jth row of C.
%
%    See also
%    GMMACTIV, KMEANS, RBFFWD
%
%    Copyright (c) Ian T Nabney (1996-2001)
[ndata, dimx] = size(x);
[ncentres, dimc] = size(c);
if dimx ~= dimc
    error('Data dimension does not match dimension of centres')
end
n2 = (ones(ncentres, 1) * sum((x.^2)', 1))' + ...
  ones(ndata, 1) * sum((c.^2)',1) - ...
  2.*(x*(c'));
% Rounding errors occasionally cause negative entries in n2
if any(any(n2<0))
  n2(n2<0) = 0;
end