Description of gmmprob
Home > ReBEL-0.2.7 > netlab > gmmprob.m
gmmprob
PURPOSE
GMMPROB Computes the data probability for a Gaussian mixture model.
SYNOPSIS
function prob = gmmprob(mix, x)
DESCRIPTION
GMMPROB Computes the data probability for a Gaussian mixture model.
    Description
     This function computes the unconditional data density P(X) for a
    Gaussian mixture model.  The data structure MIX defines the mixture
    model, while the matrix X contains the data vectors.  Each row of X
    represents a single vector.
    See also
    GMM, GMMPOST, GMMACTIV
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
gmmactiv GMMACTIV Computes the activations of a Gaussian mixture model.
This function is called by:
demgmm2 DEMGMM1 Demonstrate density modelling with a Gaussian mixture model.
demgmm3 DEMGMM3 Demonstrate density modelling with a Gaussian mixture model.
demgmm4 DEMGMM4 Demonstrate density modelling with a Gaussian mixture model.
demgpot DEMGPOT Computes the gradient of the negative log likelihood for a mixture model.
demmdn1 DEMMDN1 Demonstrate fitting a multi-valued function using a Mixture Density Network.
dempot DEMPOT Computes the negative log likelihood for a mixture model.
gmmem GMMEM EM algorithm for Gaussian mixture model.
gtmprob GTMPROB Probability for data under a GTM.
SOURCE CODE
function prob = gmmprob(mix, x)
%GMMPROB Computes the data probability for a Gaussian mixture model.
%
%    Description
%     This function computes the unconditional data density P(X) for a
%    Gaussian mixture model.  The data structure MIX defines the mixture
%    model, while the matrix X contains the data vectors.  Each row of X
%    represents a single vector.
%
%    See also
%    GMM, GMMPOST, GMMACTIV
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check that inputs are consistent
errstring = consist(mix, 'gmm', x);
if ~isempty(errstring)
  error(errstring);
end
% Compute activations
a = gmmactiv(mix, x);
% Form dot product with priors
prob = a * (mix.priors)';