Description of gmmpost
Home > ReBEL-0.2.7 > netlab > gmmpost.m
gmmpost
PURPOSE
GMMPOST Computes the class posterior probabilities of a Gaussian mixture model.
SYNOPSIS
function [post, a] = gmmpost(mix, x)
DESCRIPTION
GMMPOST Computes the class posterior probabilities of a Gaussian mixture model.
    Description
    This function computes the posteriors POST (i.e. the probability of
    each component conditioned on the data P(J|X)) for a Gaussian mixture
    model.   The data structure MIX defines the mixture model, while the
    matrix X contains the data vectors.  Each row of X represents a
    single vector.
    See also
    GMM, GMMACTIV, GMMPROB
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
gmmactiv GMMACTIV Computes the activations of a Gaussian mixture model.
This function is called by:
demev2 DEMEV2 Demonstrate Bayesian classification for the MLP.
demgmm1 DEMGMM1 Demonstrate EM for Gaussian mixtures.
demmlp2 DEMMLP2 Demonstrate simple classification using a multi-layer perceptron
gmmem GMMEM EM algorithm for Gaussian mixture model.
gtmpost GTMPOST Latent space responsibility for data in a GTM.
SOURCE CODE
function [post, a] = gmmpost(mix, x)
%GMMPOST Computes the class posterior probabilities of a Gaussian mixture model.
%
%    Description
%    This function computes the posteriors POST (i.e. the probability of
%    each component conditioned on the data P(J|X)) for a Gaussian mixture
%    model.   The data structure MIX defines the mixture model, while the
%    matrix X contains the data vectors.  Each row of X represents a
%    single vector.
%
%    See also
%    GMM, GMMACTIV, GMMPROB
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check that inputs are consistent
errstring = consist(mix, 'gmm', x);
if ~isempty(errstring)
  error(errstring);
end
ndata = size(x, 1);
a = gmmactiv(mix, x);
post = (ones(ndata, 1)*mix.priors).*a;
s = sum(post, 2);
if any(s==0)
   warning('Some zero posterior probabilities')
   % Set any zeros to one before dividing
   zero_rows = find(s==0);
   s = s + (s==0);
   post(zero_rows, :) = 1/mix.ncentres;
end
post = post./(s*ones(1, mix.ncentres));