Description of gppak
Home > ReBEL-0.2.7 > netlab > gppak.m
gppak
PURPOSE
GPPAK Combines GP hyperparameters into one vector.
SYNOPSIS
function hp = gppak(net)
DESCRIPTION
GPPAK    Combines GP hyperparameters into one vector.
    Description
    HP = GPPAK(NET) takes a Gaussian Process data structure NET and
    combines the hyperparameters into a single row vector HP.
    See also
    GP, GPUNPAK, GPFWD, GPERR, GPGRAD
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
This function is called by:
gperr GPERR Evaluate error function for Gaussian Process.
gpgrad GPGRAD Evaluate error gradient for Gaussian Process.
SOURCE CODE
function hp = gppak(net)
%GPPAK    Combines GP hyperparameters into one vector.
%
%    Description
%    HP = GPPAK(NET) takes a Gaussian Process data structure NET and
%    combines the hyperparameters into a single row vector HP.
%
%    See also
%    GP, GPUNPAK, GPFWD, GPERR, GPGRAD
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check arguments for consistency
errstring = consist(net, 'gp');
if ~isempty(errstring);
  error(errstring);
end
hp = [net.bias, net.noise, net.inweights, net.fpar];