Description of gtmmag
Home > ReBEL-0.2.7 > netlab > gtmmag.m
gtmmag
PURPOSE
GTMMAG Magnification factors for a GTM
SYNOPSIS
function mags = gtmmag(net, latent_data)
DESCRIPTION
GTMMAG    Magnification factors for a GTM
    Description
     MAGS = GTMMAG(NET, LATENTDATA) takes a GTM structure NET, and
    computes the magnification factors for each point the latent space
    contained in LATENTDATA.
    See also
    GTM, GTMPOST, GTMLMEAN
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
rbfjacob RBFJACOB Evaluate derivatives of RBF network outputs with respect to inputs.
This function is called by:
demgtm2 DEMGTM2 Demonstrate GTM for visualisation.
SOURCE CODE
function mags = gtmmag(net, latent_data)
%GTMMAG    Magnification factors for a GTM
%
%    Description
%     MAGS = GTMMAG(NET, LATENTDATA) takes a GTM structure NET, and
%    computes the magnification factors for each point the latent space
%    contained in LATENTDATA.
%
%    See also
%    GTM, GTMPOST, GTMLMEAN
%
%    Copyright (c) Ian T Nabney (1996-2001)
errstring = consist(net, 'gtm');
if ~isempty(errstring)
  error(errstring);
end
Jacs = rbfjacob(net.rbfnet, latent_data);
nlatent = size(latent_data, 1);
mags = zeros(nlatent, 1);
temp = zeros(net.rbfnet.nin, net.rbfnet.nout);
for m = 1:nlatent
  temp = squeeze(Jacs(m, :, :));  % Turn into a 2d matrix
  mags(m) = sqrt(det(temp*temp'));
end