Description of gtmpost
Home > ReBEL-0.2.7 > netlab > gtmpost.m
gtmpost
PURPOSE
GTMPOST Latent space responsibility for data in a GTM.
SYNOPSIS
function [post, a] = gtmpost(net, data)
DESCRIPTION
GTMPOST Latent space responsibility for data in a GTM.
    Description
     POST = GTMPOST(NET, DATA) takes a GTM structure NET, and computes
    the  responsibility at each latent space sample point NET.X for each
    data point in DATA.
    [POST, A] = GTMPOST(NET, DATA) also returns the activations A of the
    GMM NET.GMMNET as computed by GMMPOST.
    See also
    GTM, GTMEM, GTMLMEAN, GMLMODE, GMMPROB
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
gmmpost GMMPOST Computes the class posterior probabilities of a Gaussian mixture model.
rbffwd RBFFWD Forward propagation through RBF network with linear outputs.
This function is called by:
demgtm2 DEMGTM2 Demonstrate GTM for visualisation.
gtmem GTMEM EM algorithm for Generative Topographic Mapping.
gtmlmean GTMLMEAN Mean responsibility for data in a GTM.
gtmlmode GTMLMODE Mode responsibility for data in a GTM.
SOURCE CODE
function [post, a] = gtmpost(net, data)
%GTMPOST Latent space responsibility for data in a GTM.
%
%    Description
%     POST = GTMPOST(NET, DATA) takes a GTM structure NET, and computes
%    the  responsibility at each latent space sample point NET.X for each
%    data point in DATA.
%
%    [POST, A] = GTMPOST(NET, DATA) also returns the activations A of the
%    GMM NET.GMMNET as computed by GMMPOST.
%
%    See also
%    GTM, GTMEM, GTMLMEAN, GMLMODE, GMMPROB
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check for consistency
errstring = consist(net, 'gtm', data);
if ~isempty(errstring)
  error(errstring);
end
net.gmmnet.centres = rbffwd(net.rbfnet, net.X);
[post, a] = gmmpost(net.gmmnet, data);