Description of gtmprob
Home > ReBEL-0.2.7 > netlab > gtmprob.m
gtmprob
PURPOSE
GTMPROB Probability for data under a GTM.
SYNOPSIS
function prob = gtmprob(net, data)
DESCRIPTION
GTMPROB Probability for data under a GTM.
    Description
     PROB = GTMPROB(NET, DATA) takes a GTM structure NET, and computes
    the probability of each point in the dataset DATA.
    See also
    GTM, GTMEM, GTMLMEAN, GTMLMODE, GTMPOST
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
gmmprob GMMPROB Computes the data probability for a Gaussian mixture model.
rbffwd RBFFWD Forward propagation through RBF network with linear outputs.
This function is called by:
gtmem GTMEM EM algorithm for Generative Topographic Mapping.
SOURCE CODE
function prob = gtmprob(net, data)
%GTMPROB Probability for data under a GTM.
%
%    Description
%     PROB = GTMPROB(NET, DATA) takes a GTM structure NET, and computes
%    the probability of each point in the dataset DATA.
%
%    See also
%    GTM, GTMEM, GTMLMEAN, GTMLMODE, GTMPOST
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check for consistency
errstring = consist(net, 'gtm', data);
if ~isempty(errstring)
  error(errstring);
end
net.gmmnet.centres = rbffwd(net.rbfnet, net.X);
prob = gmmprob(net.gmmnet, data);