Description of maxitmess
Home > ReBEL-0.2.7 > netlab > maxitmess.m
maxitmess
PURPOSE
MAXITMESS Create a standard error message when training reaches max. iterations.
SYNOPSIS
function s = maxitmess()
DESCRIPTION
MAXITMESS Create a standard error message when training reaches max. iterations.
    Description
    S = MAXITMESS returns a standard string that it used by training
    algorithms when the maximum number of iterations (as specified in
    OPTIONS(14) is reached.
    See also
    CONJGRAD, GLMTRAIN, GMMEM, GRADDESC, GTMEM, KMEANS, OLGD, QUASINEW, SCG
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
conjgrad CONJGRAD Conjugate gradients optimization.
glmtrain GLMTRAIN Specialised training of generalized linear model
gmmem GMMEM EM algorithm for Gaussian mixture model.
graddesc GRADDESC Gradient descent optimization.
gtmem GTMEM EM algorithm for Generative Topographic Mapping.
kmeans KMEANS Trains a k means cluster model.
olgd OLGD On-line gradient descent optimization.
quasinew QUASINEW Quasi-Newton optimization.
scg SCG Scaled conjugate gradient optimization.
SOURCE CODE
function s = maxitmess()
%MAXITMESS Create a standard error message when training reaches max. iterations.
%
%    Description
%    S = MAXITMESS returns a standard string that it used by training
%    algorithms when the maximum number of iterations (as specified in
%    OPTIONS(14) is reached.
%
%    See also
%    CONJGRAD, GLMTRAIN, GMMEM, GRADDESC, GTMEM, KMEANS, OLGD, QUASINEW, SCG
%
%    Copyright (c) Ian T Nabney (1996-2001)
s = 'Maximum number of iterations has been exceeded';