Description of mlpderiv
Home > ReBEL-0.2.7 > netlab > mlpderiv.m
mlpderiv
PURPOSE
MLPDERIV Evaluate derivatives of network outputs with respect to weights.
SYNOPSIS
function g = mlpderiv(net, x)
DESCRIPTION
MLPDERIV Evaluate derivatives of network outputs with respect to weights.
   Description
   G = MLPDERIV(NET, X) takes a network data structure NET and a matrix
   of input vectors X and returns a three-index matrix G whose I, J, K
   element contains the derivative of network output K with respect to
   weight or bias parameter J for input pattern I. The ordering of the
   weight and bias parameters is defined by MLPUNPAK.
   See also
   MLP, MLPPAK, MLPGRAD, MLPBKP
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
mlpbkp MLPBKP Backpropagate gradient of error function for 2-layer network.
mlpfwd MLPFWD Forward propagation through 2-layer network.
This function is called by:
SOURCE CODE
function g = mlpderiv(net, x)
%MLPDERIV Evaluate derivatives of network outputs with respect to weights.
%
%   Description
%   G = MLPDERIV(NET, X) takes a network data structure NET and a matrix
%   of input vectors X and returns a three-index matrix G whose I, J, K
%   element contains the derivative of network output K with respect to
%   weight or bias parameter J for input pattern I. The ordering of the
%   weight and bias parameters is defined by MLPUNPAK.
%
%   See also
%   MLP, MLPPAK, MLPGRAD, MLPBKP
%
%   Copyright (c) Ian T Nabney (1996-2001)
% Check arguments for consistency
errstring = consist(net, 'mlp', x);
if ~isempty(errstring);
  error(errstring);
end
[y, z] = mlpfwd(net, x);
ndata = size(x, 1);
if isfield(net, 'mask')
  nwts = size(find(net.mask), 1);
  temp = zeros(1, net.nwts);
else
  nwts = net.nwts;
end
g = zeros(ndata, nwts, net.nout);
for k = 1 : net.nout
  delta = zeros(1, net.nout);
  delta(1, k) = 1;
  for n = 1 : ndata
    if isfield(net, 'mask')
      temp = mlpbkp(net, x(n, :), z(n, :), delta);
      g(n, :, k) = temp(logical(net.mask));
    else
      g(n, :, k) = mlpbkp(net, x(n, :), z(n, :),...
    delta);
    end
  end
end