Description of mlpfwd
Home > ReBEL-0.2.7 > netlab > mlpfwd.m
mlpfwd
PURPOSE
MLPFWD Forward propagation through 2-layer network.
SYNOPSIS
function [y, z, a] = mlpfwd(net, x)
DESCRIPTION
MLPFWD    Forward propagation through 2-layer network.
    Description
    Y = MLPFWD(NET, X) takes a network data structure NET together with a
    matrix X of input vectors, and forward propagates the inputs through
    the network to generate a matrix Y of output vectors. Each row of X
    corresponds to one input vector and each row of Y corresponds to one
    output vector.
    [Y, Z] = MLPFWD(NET, X) also generates a matrix Z of the hidden unit
    activations where each row corresponds to one pattern.
    [Y, Z, A] = MLPFWD(NET, X) also returns a matrix A  giving the summed
    inputs to each output unit, where each row corresponds to one
    pattern.
    See also
    MLP, MLPPAK, MLPUNPAK, MLPERR, MLPBKP, MLPGRAD
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
This function is called by:
demard DEMARD Automatic relevance determination using the MLP.
demev1 DEMEV1 Demonstrate Bayesian regression for the MLP.
demev2 DEMEV2 Demonstrate Bayesian classification for the MLP.
demhmc2 DEMHMC2 Demonstrate Bayesian regression with Hybrid Monte Carlo sampling.
demhmc3 DEMHMC3 Demonstrate Bayesian regression with Hybrid Monte Carlo sampling.
demmdn1 DEMMDN1 Demonstrate fitting a multi-valued function using a Mixture Density Network.
demmlp1 DEMMLP1 Demonstrate simple regression using a multi-layer perceptron
demmlp2 DEMMLP2 Demonstrate simple classification using a multi-layer perceptron
demolgd1 DEMOLGD1 Demonstrate simple MLP optimisation with on-line gradient descent
demprior DEMPRIOR Demonstrate sampling from a multi-parameter Gaussian prior.
demtrain DEMTRAIN Demonstrate training of MLP network.
mdnfwd MDNFWD Forward propagation through Mixture Density Network.
mlpderiv MLPDERIV Evaluate derivatives of network outputs with respect to weights.
mlperr MLPERR Evaluate error function for 2-layer network.
mlpevfwd MLPEVFWD Forward propagation with evidence for MLP
mlpgrad MLPGRAD Evaluate gradient of error function for 2-layer network.
mlphdotv MLPHDOTV Evaluate the product of the data Hessian with a vector.
SOURCE CODE
function [y, z, a] = mlpfwd(net, x)
%MLPFWD    Forward propagation through 2-layer network.
%
%    Description
%    Y = MLPFWD(NET, X) takes a network data structure NET together with a
%    matrix X of input vectors, and forward propagates the inputs through
%    the network to generate a matrix Y of output vectors. Each row of X
%    corresponds to one input vector and each row of Y corresponds to one
%    output vector.
%
%    [Y, Z] = MLPFWD(NET, X) also generates a matrix Z of the hidden unit
%    activations where each row corresponds to one pattern.
%
%    [Y, Z, A] = MLPFWD(NET, X) also returns a matrix A  giving the summed
%    inputs to each output unit, where each row corresponds to one
%    pattern.
%
%    See also
%    MLP, MLPPAK, MLPUNPAK, MLPERR, MLPBKP, MLPGRAD
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check arguments for consistency
errstring = consist(net, 'mlp', x);
if ~isempty(errstring);
  error(errstring);
end
ndata = size(x, 1);
z = tanh(x*net.w1 + ones(ndata, 1)*net.b1);
a = z*net.w2 + ones(ndata, 1)*net.b2;
switch net.outfn
  case 'linear'    % Linear outputs
    y = a;
  case 'logistic'  % Logistic outputs
    % Prevent overflow and underflow: use same bounds as mlperr
    % Ensure that log(1-y) is computable: need exp(a) > eps
    maxcut = -log(eps);
    % Ensure that log(y) is computable
    mincut = -log(1/realmin - 1);
    a = min(a, maxcut);
    a = max(a, mincut);
    y = 1./(1 + exp(-a));
  case 'softmax'   % Softmax outputs
    % Prevent overflow and underflow: use same bounds as glmerr
    % Ensure that sum(exp(a), 2) does not overflow
    maxcut = log(realmax) - log(net.nout);
    % Ensure that exp(a) > 0
    mincut = log(realmin);
    a = min(a, maxcut);
    a = max(a, mincut);
    temp = exp(a);
    y = temp./(sum(temp, 2)*ones(1, net.nout));
  otherwise
    error(['Unknown activation function ', net.outfn]);
end