Description of mlpunpak
Home > ReBEL-0.2.7 > netlab > mlpunpak.m
mlpunpak
PURPOSE
MLPUNPAK Separates weights vector into weight and bias matrices.
SYNOPSIS
function net = mlpunpak(net, w)
DESCRIPTION
MLPUNPAK Separates weights vector into weight and bias matrices.
    Description
    NET = MLPUNPAK(NET, W) takes an mlp network data structure NET and  a
    weight vector W, and returns a network data structure identical to
    the input network, except that the first-layer weight matrix W1, the
    first-layer bias vector B1, the second-layer weight matrix W2 and the
    second-layer bias vector B2 have all been set to the corresponding
    elements of W.
    See also
    MLP, MLPPAK, MLPFWD, MLPERR, MLPBKP, MLPGRAD
CROSS-REFERENCE INFORMATION
This function calls:
consist CONSIST Check that arguments are consistent.
This function is called by:
demhmc2 DEMHMC2 Demonstrate Bayesian regression with Hybrid Monte Carlo sampling.
demhmc3 DEMHMC3 Demonstrate Bayesian regression with Hybrid Monte Carlo sampling.
mdnunpak MDNUNPAK Separates weights vector into weight and bias matrices.
mlphdotv MLPHDOTV Evaluate the product of the data Hessian with a vector.
mlpinit MLPINIT Initialise the weights in a 2-layer feedforward network.
SOURCE CODE
function net = mlpunpak(net, w)
%MLPUNPAK Separates weights vector into weight and bias matrices.
%
%    Description
%    NET = MLPUNPAK(NET, W) takes an mlp network data structure NET and  a
%    weight vector W, and returns a network data structure identical to
%    the input network, except that the first-layer weight matrix W1, the
%    first-layer bias vector B1, the second-layer weight matrix W2 and the
%    second-layer bias vector B2 have all been set to the corresponding
%    elements of W.
%
%    See also
%    MLP, MLPPAK, MLPFWD, MLPERR, MLPBKP, MLPGRAD
%
%    Copyright (c) Ian T Nabney (1996-2001)
% Check arguments for consistency
errstring = consist(net, 'mlp');
if ~isempty(errstring);
  error(errstring);
end
if net.nwts ~= length(w)
  error('Invalid weight vector length')
end
nin = net.nin;
nhidden = net.nhidden;
nout = net.nout;
mark1 = nin*nhidden;
net.w1 = reshape(w(1:mark1), nin, nhidden);
mark2 = mark1 + nhidden;
net.b1 = reshape(w(mark1 + 1: mark2), 1, nhidden);
mark3 = mark2 + nhidden*nout;
net.w2 = reshape(w(mark2 + 1: mark3), nhidden, nout);
mark4 = mark3 + nout;
net.b2 = reshape(w(mark3 + 1: mark4), 1, nout);