Description of nethess
Home > ReBEL-0.2.7 > netlab > nethess.m
nethess
PURPOSE
NETHESS Evaluate network Hessian
SYNOPSIS
function [h, varargout] = nethess(w, net, x, t, varargin)
DESCRIPTION
NETHESS Evaluate network Hessian
    Description
    H = NETHESS(W, NET, X, T) takes a weight vector W and a network data
    structure NET, together with the matrix X of input vectors and the
    matrix T of target vectors, and returns the value of the Hessian
    evaluated at W.
    [E, VARARGOUT] = NETHESS(W, NET, X, T, VARARGIN) also returns any
    additional return values from the network Hessian function, and
    passes additional arguments to that function.
    See also
    NETERR, NETGRAD, NETOPT
CROSS-REFERENCE INFORMATION
This function calls:
netunpak NETUNPAK Separates weights vector into weight and bias matrices.
This function is called by:
evidence EVIDENCE Re-estimate hyperparameters using evidence approximation.
fevbayes FEVBAYES Evaluate Bayesian regularisation for network forward propagation.
hesschek HESSCHEK Use central differences to confirm correct evaluation of Hessian matrix.
SOURCE CODE
function [h, varargout] = nethess(w, net, x, t, varargin)
%NETHESS Evaluate network Hessian
%
%    Description
%
%    H = NETHESS(W, NET, X, T) takes a weight vector W and a network data
%    structure NET, together with the matrix X of input vectors and the
%    matrix T of target vectors, and returns the value of the Hessian
%    evaluated at W.
%
%    [E, VARARGOUT] = NETHESS(W, NET, X, T, VARARGIN) also returns any
%    additional return values from the network Hessian function, and
%    passes additional arguments to that function.
%
%    See also
%    NETERR, NETGRAD, NETOPT
%
%    Copyright (c) Ian T Nabney (1996-2001)
hess_str = [net.type, 'hess'];
net = netunpak(net, w);
[s{1:nargout}] = feval(hess_str, net, x, t, varargin{:});
h = s{1};
for i = 2:nargout
  varargout{i-1} = s{i};
end