Description of netpak
Home > ReBEL-0.2.7 > netlab > netpak.m
netpak
PURPOSE
NETPAK Combines weights and biases into one weights vector.
SYNOPSIS
function w = netpak(net)
DESCRIPTION
NETPAK    Combines weights and biases into one weights vector.
    Description
    W = NETPAK(NET) takes a network data structure NET and combines the
    component weight matrices  into a single row vector W. The facility
    to switch between these two representations for the network
    parameters is useful, for example, in training a network by error
    function minimization, since a single vector of parameters can be
    handled by general-purpose optimization routines.  This function also
    takes into account a MASK defined as a field in NET by removing any
    weights that correspond to entries of 0 in the mask.
    See also
    NET, NETUNPAK, NETFWD, NETERR, NETGRAD
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demev3 DEMEV3 Demonstrate Bayesian regression for the RBF.
errbayes ERRBAYES Evaluate Bayesian error function for network.
evidence EVIDENCE Re-estimate hyperparameters using evidence approximation.
fevbayes FEVBAYES Evaluate Bayesian regularisation for network forward propagation.
gbayes GBAYES Evaluate gradient of Bayesian error function for network.
glmtrain GLMTRAIN Specialised training of generalized linear model
hesschek HESSCHEK Use central differences to confirm correct evaluation of Hessian matrix.
netopt NETOPT Optimize the weights in a network model.
rbftrain RBFTRAIN Two stage training of RBF network.
SOURCE CODE
function w = netpak(net)
%NETPAK    Combines weights and biases into one weights vector.
%
%    Description
%    W = NETPAK(NET) takes a network data structure NET and combines the
%    component weight matrices  into a single row vector W. The facility
%    to switch between these two representations for the network
%    parameters is useful, for example, in training a network by error
%    function minimization, since a single vector of parameters can be
%    handled by general-purpose optimization routines.  This function also
%    takes into account a MASK defined as a field in NET by removing any
%    weights that correspond to entries of 0 in the mask.
%
%    See also
%    NET, NETUNPAK, NETFWD, NETERR, NETGRAD
%
%    Copyright (c) Ian T Nabney (1996-2001)
pakstr = [net.type, 'pak'];
w = feval(pakstr, net);
% Return masked subset of weights
if (isfield(net, 'mask'))
   w = w(logical(net.mask));
end